### ISSUE TITLE
[Linux] PC Hangs after minutes of playing Tf2

### ISSUE THREAD

**Issue by Lukypie** [ValveSoftware/Source-1-Games#1943]
after the latest tf2 update, Played yesterday and there was no problem

**Comment by portify** [comment]
TF2 ran fine before the update for me, but after the update it now freezes the system (any IO (graphical, keyboard, etc), etc) after playing for several minutes. Managing to get it to respond to an ACPI shutdown during a freeze gets it stuck in a pseudo-shutdown-phase where the following message is repeated every ~22s:

    "NMI watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [steamerrorrepor:3203]"

This is completely consistent so far. Every time I try to play, this happens after a few minutes. Not *certain* if it's the same issue, but it sure sounds like it. I'm using Arch Linux, though, which I'm aware is not "officially" supported.

**Comment by Tele42** [comment]
Are either of you using nvidia 358?

**Comment by Lukypie** [comment]
nope, Im using radeon open source drivers.

**Comment by Lukypie** [comment]
Can't find anything in the kernel log.
Also, when it hangs, sysrq keys are not working, also the reboot physical button. What the hell? I have to re-plug the socket.

**Comment by Lukypie** [comment]
finally got something from the dmesg 
http://m.imgur.com/a/FacOE

**Comment by portify** [comment]
Yep, thought it was a similar issue: completely stalling/locking up

**Comment by Lukypie** [comment]
Another detailed DMESG after runned tf2.
Basically, the kernel module crashes. 
Tried to downgrade the arch repo to the "stable" one instead the testing but same happened.

http://pastebin.com/wMnqkCch

**Comment by Tele42** [comment]
This should also be reported to the video driver devs, any opengl application should not be able to cause this kind of behavior in the driver.

**Comment by Lukypie** [comment]
I don't really know. Half life 2 is running pretty fine

**Comment by Lukypie** [comment]
Well, same thing is happening with ubuntu. Guess it's a really bad tf2 programming problem.

**Comment by jeh72** [comment]
Yup, same thing here, with open source radeon.  Ring 0 stalled for more than ... msec.  This only happens with my radeon laptop (firepro m6100/HD 8950m), and not with my desktop r9 290.  Happens with multiple distros, multiple kernels, multiple mesa versions.  Only tf2 seems to be affected.
It doesn't look like there is anything in the xorg log.  I'm attaching the relevant section from dmesg for when the crash happened.
[tf2_crash.txt](https://github.com/ValveSoftware/Source-1-Games/files/72583/tf2_crash.txt)

**Comment by Lukypie** [comment]
http://pastebin.com/xPtiXpk0

Got another info

**Comment by jeh72** [comment]
I'm finding that this crash will sometimes, depending on the distro, not completely crash the pc.  It still causes the GPU to reset with broken DPM though, so playing the game with more than 20 fps is not possible until after a reboot.

With updated Fedora 23 I also managed to get it to crash the exact same way with the HD 7790 (Bonaire) in my wife's PC!  The m6100 gpu in the laptop is also Bonaire.  Lukypie, do you know if your GPU is based on the bonaire chip?  That would include GPU's such as the HD 7790, R9 260/260x, R9 360, and probably a few more. 

After-crash dmesg for HD 7790/fedora 23:
http://pastebin.com/SbJiLCpF

**Comment by Lukypie** [comment]
i sold my old PC, i'm buying a r9 380 hoping that it will be better

**Comment by jeh72** [comment]
Oh, ok.  Just fyi, with the r9 380 you will need to use the fglrx driver for now if you want to game on linux.  Open source radeon doesn't re-clock properly with Tonga GPU's at present.

**Comment by Half-Shot** [comment]
Same problem with the ol HD 7950

**Comment by Lukypie** [comment]
Yea, I know, I don't care about energy saving honestly lol but amdgpu driver is a great thing.
Anyway, the problem is with the radeon driver on 7xxx/Southern Islands and the latest tf2 update. Can it be resolved from the driver side/game side? 
I don't really know what can be the real problem. If with other cards and with the amd proprietary driver  there is no problem...

**Comment by victoredwardocallaghan** [comment]
Hi,

This is not the fault of the game but rather a kernel bug and possibly a mesa bug. Some draw call is causing the GPU lockup and soft reset. Upon resetting the kernel tries to recreate files in sysfs that already exist hence the kernel oops.

I can fix the kernel oops if it has not been fixed already? Which kernel rev. are you using on which distro?

Regarding the GPU hang can you please report that as a bug at http://bugs.freedesktop.org/ with your kernel and mesa versions, the distro you are using, and the ring 0 hang you pasted here http://pastebin.com/wMnqkCch  we will likely need a apitrace as well from the game to reproduce but start with the rest of the information presented in a coherent way in your report.

Thanks,
Edward.

**Comment by jeh72** [comment]
I'll try to get more crash info when I am home from work.  Here is a kerneloops page that was generated from the last crash:
https://retrace.fedoraproject.org/faf/reports/955260/
How do I get an apitrace from TF2?

**Comment by jeh72** [comment]
Game still crashes after today's update...

**Comment by Half-Shot** [comment]
Still crashing today. Ring 0 stalled error

**Comment by RussianNeuroMancer** [comment]
Seems like this is relevant driver report: https://bugs.freedesktop.org/show_bug.cgi?id=93649

**Comment by MJDSys** [comment]
Hi all,

I've seen this as well, and created the bug report.  For those having issues, can you please state what your graphics card is?  Mine is a 7970 for the record.

For anyone who feels comfortable recompiling the kernel, could you try the patch I've posted here: https://paste.kde.org/preuoweaf .  Please note that it is a giant hack, and may cause other issues (including eating your data).  I also recommend using it against the 4.4 kernel, as it may fix another bug I've seen (untested by me yet).

Thanks!

**Comment by jeh72** [comment]
I just got a crash with my R9 290 (hawaii).  Looks like all radeonsi may be affected.

**Comment by jeh72** [comment]
Still getting crashes/hangs after Feb 2nd update

**Comment by Rosco-github** [comment]
Same problem here since December, on a fedora 23 on a HD7970.

**Comment by TheSamsai** [comment]
R7 370 here, also seeing this issue.

**Comment by Jheguy2** [comment]
R9 290 here. Same issue, only happens in TF2.

**Comment by jeh72** [comment]
This is still happening, more than four months later!! It looks like all pc's that use the radeonsi driver are affected.  This is the *only* game that does this.

**Comment by Lukypie** [comment]
i don't know. Also with amdgpu I'm having the same issue, seems like there is a mesa code shared with all AMD gpus which causes this problem, and only with tf2.
I want to try this with the AMD GPU pro, which uses amdgpu but does not share anything with Mesa. (Or no? I didn't understood this honestly but I want to try)

**Comment by Half-Shot** [comment]
I played with a r600 and it's been fine. (5770HD)

**Comment by Jheguy2** [comment]
Still broken for me. Totally crashed my entire graphics stack.

**Comment by Mezentium** [comment]
Still broken, Debian Testing, 4.5 kernel, AMD A8 7600, Mesa 11.1.3

**Comment by jeh72** [comment]
I've given up waiting for valve to fix this. The Mac and Linux versions of this game seem like afterthoughts at this point.

**Comment by Rosco-github** [comment]
Same bug than before after upgrading to fedora 24 beta. Crashed after 3 minutes.

OpenGL core profile version string: 4.1 (Core Profile) Mesa 11.2.1 (git-79b0e13)
kernel 4.5.4-300.fc24.x86_64

**Comment by Tele42** [comment]
Another mesa bug report has been filed: https://bugs.freedesktop.org/show_bug.cgi?id=95308.

**Comment by xalalau** [comment]
Same thing here. Ubuntu 16.04 + Radeon HD 7730M + OpenGL core profile version string: 4.1 (Core Profile) Mesa 11.3.0-devel (git-998829f 2016-05-25 xenial-oibaf-ppa)

**Comment by BoctorPoo** [comment]
Experienced on both the Linux 4.4 and 4.5 kernels on Ubuntu (Xfce) 15.10, Ubuntu (Xfce) 16.04, and Fedora 24 (Workstation Beta). This is a pretty painful blow to AMD users, because of the "new" driver model AMD is rolling out to replace fglrx. My error is the same ring zero stalling error as everyone else's, and it indeed only happens on Team Fortress 2 after a short session. Did all the contractors who worked on ToGL just up and leave?

**Comment by steamlinux** [comment]
I have similar bug with L4D2 (I don't play TF2)

**Comment by BoctorPoo** [comment]
I just encountered the same freeze while playing Team Fortress 2 in Wine 1.9, happens in both dxlevel 90 and 85. I felt conflicted as to whether this is out of scope, but it's still only happening on the AMDGPU driver. What could have happened on 12/18/15 that caused this?

**Comment by JelloMonster118** [comment]
If what you mean by PC hanging is that the system completely freezes and doesn't unfreeze, I get that too. I play for varying amounts of time on any graphical setting, then the game freezes and loops the last half-second or so of audio. I have to reset my computer (maybe it eventually automatically turns off? I don't have the patience to wait more than a few minutes to see if the freeze ends).
I have an AMD card (R9 380) in my computer but no driver installed because Ubuntu 16.04 doesn't have a supported driver, so I assume my PC is using the Intel graphics on my i3-6100. Will rolling back to 15.04 and installing AMD's drivers fix this issue? I want to be able to play for more than 5 minutes at a time.

**Comment by stevethepocket** [comment]
This has been happening for me on my new Kubuntu setup. It crashes the graphic driver with an error on a black screen (which doesn't stay up long enough to jot down or take a photo of), _logs me out_ somehow, and then the driver must not fully kick back in because I get super corrupted graphics if I try to start the game again after that. Is anyone else getting the corrupted graphics?

_Left 4 Dead 2_ seems totally stable, or at least it did the other day — I haven't tried it since the latest patch.

**Comment by Mezentium** [comment]
Tested with Debian Testing 4.6.1 kernel. TF2 still has the freeze, but it doesn't bring the system down like it did before and recovers from the freeze this time. Its ugly, but it works now. Valve needs to fix TF2 since this doesn't happen with DOTA

**Comment by jeh72** [comment]
Just tested with Gentoo, with mesa-11.2.1, llvm-3.8.0, R9 290.

Kernel 4.6.3, using radeon/radeonsi driver: Still freezes after about 10 minutes.  No change.

Kernel 4.6.3, using amdgpu with CIK enabled:  Did not freeze after about 20 minutes of gameplay, **however** with the amdgpu driver my R9 290 is stuck at the minimum clock speed.

Once they fix hawaii reclocking with amdgpu it will be interesting to see if the freezing comes back.

Has anyone tested tf2 with amdgpu and a Tonga or Fiji card?

**Comment by jeh72** [comment]
Ok, tested it with Gentoo, mesa-12.0.1, llvm-3.8.0, kernel 4.6.3 w/ amdgpu & CIK support, Radeon HD 7790.

amdgpu and reclocking *does* work on this card, unlike my 290 above.

I got it to crash as usual with this combination.  So, this is probably an issue with mesa since it crashes with both radeon and amdgpu kernel modules.

**Comment by steamlinux** [comment]
try disable multi-core rendering in game settings, this help me with l4d2 and csgo

**Comment by bniels707** [comment]
I still see the issue with multicore rendering disabled.

**Comment by jeh72** [comment]
This may be a bit of a stretch, but could this bug be possibly related to the XCOM radeon crashing bug?
[https://bugs.freedesktop.org/show_bug.cgi?id=80419](https://bugs.freedesktop.org/show_bug.cgi?id=80419)

**Comment by bniels707** [comment]
I am affected by both issues, but I don't know enough to say they're related.

**Comment by DrakeJa** [comment]
This is an old thread but I'm still having the issue on my TONGA R9 380. It seems whenever I try to do damage to an enemy it hangs, loops and get's stuck until I have to do the old hole the power button down trick. It may be a problem with Mesa 11.XX. I'll try getting Mesa 12.1 working on Debian Testing and see if that works.

**Comment by amarildojr** [comment]
@DrakeJa This is a very weird issue, because I don't really know where it is. I think it's not in Mesa, and here's why:

* On Debian Jessie with kernel 3.16 and Mesa 10.3, the problem doesn't happen;
* On the same Debian, but with mesa backported, the problem also doesn't happen;
* On the same Debian with Mesa backported and the Kernel backported, the problem still doesn't happen;
* On Arch Linux with Mesa downgraded to 10.3, the problem happens;
* On the same Arch Linux with Mesa and Kernel downgraded, the problem still happens;
* I'm not 100% sure I downgraded the Firmware on Arch, but I'll try today since I'm testing a few drivers in Linux;
* I have a vague memory about downgrading the kernel, mesa, and the firmware, and the issue was still there;
* On vanilla Arch with Catalyst/FGLRX, the problem doesn't happen;

So I do think this issue is much bigger than everybody things and only happens with a certain combination of Mesa, Kernel, Firmware, and possibly libdrm, llvm, and other pieces of software as well.

What I really think is that VALVe should investigate this.

**Comment by amarildojr** [comment]
It's really interesting that VALVe introduced Texture Streaming into TF2 and this bug appeared out of nowhere.

**Comment by jeh72** [comment]
@amarildojr I've encountered the freezing issue with Debian Jessie.  I'm pretty sure it happened with the stable and backported kernel with backported Mesa 11.

**Comment by amarildojr** [comment]
Weird that for me it didn't. What card model do you have? Mine's a Sapphire R9 270X DualX OC Edition.

**Comment by jeh72** [comment]
@amarildojr Mine was a Bonaire-based FirePro m6100.  I'll have to try Jessie with my r9 290 too but I'm pretty sure it'll still happen there.

The fact that this problem doesn't occur with fglrx or amdgpu-pro makes me think it is a problem in mesa

**Comment by amarildojr** [comment]
But if it were a problem in Mesa, why wouldn't I see it in Jessie + backported mesa? And why doesn't it go away when I downgrade Mesa in Arch? it makes no sense to me.

**Comment by jeh72** [comment]
Have you played it for at least a half houron those? Sometimes it takes longer to show up

**Comment by amarildojr** [comment]
Oh yes :)

**Comment by Tele42** [comment]
@amarildojr, does the Debian Jessie + newer mesa configuration also have newer kernel? With the information available so far, this issue has equal probability of being a kernel regression as it is a mesa bug.

What's needed is for someone to put in the time to bisect the issue between a confirmed good state and the bug until the commit that caused the issue to appear is found.

**Comment by amarildojr** [comment]
@Tele42 See this: https://github.com/ValveSoftware/Source-1-Games/issues/1943#issuecomment-244415894

**Comment by amarildojr** [comment]
The thing is, this problem didn't start because of a Mesa update, but because of a TF2 update, so there's really no good base to start looking for a bisect. Not to mention, each sucessful bisect can easily take 13 compile/reboots; now multiply that for the number of "goods and bads" Mesa versions, Kernel versions, etc.

VALVe should be looking at this, not the users. However, it's clear that Linux-TF2 is not in their calendar ATM.

**Comment by DrakeJa** [comment]
Mine still has this issue even after several updates from VALVE. It seems like a game compatibility issue with the kernel because I'm on Debian Testing with Linux Kernel version 4. We'll just have to wait I guess...

**Comment by Tele42** [comment]
Hypothetically, if the regression was in llvm, which is used with radeonsi to compile shaders, then that could match @amarildojr's differential of the issue, with the older version of llvm not having an issue.

**Comment by amarildojr** [comment]
@Tele42 I'll try to downgrade llvm to version 3.5, the one present in Jessie. However, since Mesa is compiled against a very specific llvm version, I'll have to downgrade both. 

Expect a response within an hour or so, since there's more to test.

**Comment by jeh72** [comment]
I will try with Gentoo this weekend if needed.  It's pretty easy to downgrade llvm and recompile mesa with it.

**Comment by amarildojr** [comment]
Downgraded mesa and llvm, and my display manager (ssdm) won't start. I'll try older versions of it and lightdm as well.

>[root@amarildo test]# pacman -U $(ls *.pkg.tar.xz)
loading packages...
warning: downgrading package glu (9.0.0-4 => 9.0.0-2)
warning: downgrading package lib32-mesa (12.0.1-5 => 10.3.2-1)
warning: downgrading package lib32-mesa-libgl (12.0.1-5 => 10.3.2-1)
warning: downgrading package lib32-mesa-vdpau (12.0.1-5 => 10.3.2-1)
warning: downgrading package libtxc_dxtn (1.0.1-6 => 1.0.1-5)
warning: downgrading package llvm (3.8.1-1 => 3.5.0-1)
warning: downgrading package llvm-libs (3.8.1-1 => 3.5.0-1)
warning: downgrading package mesa (12.0.1-7 => 10.3.2-1)
warning: downgrading package mesa-libgl (12.0.1-7 => 10.3.2-1)
warning: downgrading package mesa-vdpau (12.0.1-7 => 10.3.2-1)
resolving dependencies...
looking for conflicting packages...
warning: dependency cycle detected:
warning: libtxc_dxtn will be installed before its mesa dependency

>Packages (12) glu-9.0.0-2  lib32-mesa-10.3.2-1  lib32-mesa-dri-10.3.2-1  lib32-mesa-libgl-10.3.2-1  lib32-mesa-vdpau-10.3.2-1
              libtxc_dxtn-1.0.1-5  llvm-3.5.0-1  llvm-libs-3.5.0-1  mesa-10.3.2-1  mesa-dri->10.3.2-1  mesa-libgl-10.3.2-1
              mesa-vdpau-10.3.2-1

>Total Installed Size:  176.72 MiB
Net Upgrade Size:      -66.44 MiB

>:: Proceed with installation? [Y/n] 
(12/12) checking keys in keyring                                                    [################################################] 100%
(12/12) checking package integrity                                                  [################################################] 100%
(12/12) loading package files                                                       [################################################] 100%
(12/12) checking for file conflicts                                                 [################################################] 100%
(12/12) checking available disk space                                               [################################################] 100%
:: Processing package changes...
( 1/12) downgrading llvm-libs                                                       [################################################] 100%
( 2/12) downgrading libtxc_dxtn                                                     [################################################] 100%
( 3/12) installing mesa-dri                                                         [################################################] 100%
Optional dependencies for mesa-dri
    mesa-vdpau: for accelerated video playback [installed]
( 4/12) downgrading mesa                                                            [################################################] 100%
( 5/12) downgrading mesa-libgl                                                      [################################################] 100%
( 6/12) downgrading glu                                                             [################################################] 100%
( 7/12) installing lib32-mesa-dri                                                   [################################################] 100%
Optional dependencies for lib32-mesa-dri
    lib32-mesa-vdpau: for accelerated video playback [installed]
( 8/12) downgrading lib32-mesa                                                      [################################################] 100%
( 9/12) downgrading lib32-mesa-libgl                                                [################################################] 100%
(10/12) downgrading lib32-mesa-vdpau                                                [################################################] 100%
(11/12) downgrading llvm                                                            [################################################] 100%
(12/12) downgrading mesa-vdpau                                                      [################################################] 100%
[root@amarildo test]#

**Comment by amarildojr** [comment]
Well, I can't downgrade anymore, I don't know why.

Mesa, lib32-mesa, mesa-libgl, lib32-mesa-libgl, llvm, llvm-libs, lib32-llvm-libs, xorg-server and relatives, libdrm, lib32-libdrm, and linux 3.16.... the display still won't start.

@jeh72 I guess I'll be waiting for your results then. If you could try mesa and llvm alone at first, that would be great. 

Cheers.

**Comment by RussianNeuroMancer** [comment]
Is there anyone who have this with VLIW/TeraScale GPU?

**Comment by jeh72** [comment]
Well, no luck with lower version of llvm.

I downgraded to llvm-3.5.0, but I couldn't keep the mesa version the same since newer mesa requires newer llvm.  I downgraded mesa to mesa-11.1.4 since that was the highest mesa version that works with llvm-3.5.  I loaded up tf2 and...  

If anything, I got the crash even faster this time (within 5 minutes).  Because I'm on a newer kernel (4.4) it didn't crash my whole system, but it did lock my GPU at minimum performance after it recovered which makes the game hilariously unplayable at 15-20fps. 

Also, it's amazing how much speed has improved since these earlier llvm/mesa versions.  Even before crashing the game was really slow on my setup (FX-4300 @4.4ghz, Gigabyte non-reference R9 290)

Same dmesg error, as usual:

> [14219.167066] radeon 0000:01:00.0: ring 0 stalled for more than 10196msec
>[14219.167070] radeon 0000:01:00.0: GPU lockup (current fence id 0x000000000005ff28 last fence >id 0x000000000005ff34 on ring 0)
>[14219.211818] radeon 0000:01:00.0: Saved 617 dwords of commands on ring 0.
>[14219.211835] radeon 0000:01:00.0: GPU softreset: 0x00000009
>[14219.211837] radeon 0000:01:00.0:   GRBM_STATUS=0xE5580028
>[14219.211839] radeon 0000:01:00.0:   GRBM_STATUS2=0x50000008
>[14219.211841] radeon 0000:01:00.0:   GRBM_STATUS_SE0=0x00000000
>[14219.211843] radeon 0000:01:00.0:   GRBM_STATUS_SE1=0x00000000
>[14219.211845] radeon 0000:01:00.0:   GRBM_STATUS_SE2=0xEC000000
>[14219.211847] radeon 0000:01:00.0:   GRBM_STATUS_SE3=0xEC000000
>[14219.211848] radeon 0000:01:00.0:   SRBM_STATUS=0x20000040
>[14219.211850] radeon 0000:01:00.0:   SRBM_STATUS2=0x00000000
>[14219.211852] radeon 0000:01:00.0:   SDMA0_STATUS_REG   = 0x46CEE557
>[14219.211854] radeon 0000:01:00.0:   SDMA1_STATUS_REG   = 0x46CEE557
>[14219.211856] radeon 0000:01:00.0:   CP_STAT = 0x84038600
>[14219.211857] radeon 0000:01:00.0:   CP_STALLED_STAT1 = 0x00000c00
>[14219.211859] radeon 0000:01:00.0:   CP_STALLED_STAT2 = 0x00010100
>[14219.211861] radeon 0000:01:00.0:   CP_STALLED_STAT3 = 0x00000400
>[14219.211863] radeon 0000:01:00.0:   CP_CPF_BUSY_STAT = 0x00000006
>[14219.211865] radeon 0000:01:00.0:   CP_CPF_STALLED_STAT1 = 0x00000003
>[14219.211866] radeon 0000:01:00.0:   CP_CPF_STATUS = 0x80000063
>[14219.211868] radeon 0000:01:00.0:   CP_CPC_BUSY_STAT = 0x00000000
>[14219.211870] radeon 0000:01:00.0:   CP_CPC_STALLED_STAT1 = 0x00000000
>[14219.211872] radeon 0000:01:00.0:   CP_CPC_STATUS = 0x00000000
>[14219.211874] radeon 0000:01:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x00000000
>[14219.211876] radeon 0000:01:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x00000000
>[14219.221293] radeon 0000:01:00.0: GRBM_SOFT_RESET=0x00010001
>[14219.221347] radeon 0000:01:00.0: SRBM_SOFT_RESET=0x00000100
>[14219.222502] radeon 0000:01:00.0:   GRBM_STATUS=0x00003028
>[14219.222504] radeon 0000:01:00.0:   GRBM_STATUS2=0x00000008
>[14219.222506] radeon 0000:01:00.0:   GRBM_STATUS_SE0=0x00000006
>[14219.222508] radeon 0000:01:00.0:   GRBM_STATUS_SE1=0x00000006
>[14219.222510] radeon 0000:01:00.0:   GRBM_STATUS_SE2=0x00000006
>[14219.222511] radeon 0000:01:00.0:   GRBM_STATUS_SE3=0x00000006
>[14219.222513] radeon 0000:01:00.0:   SRBM_STATUS=0x20000040
>[14219.222515] radeon 0000:01:00.0:   SRBM_STATUS2=0x00000000
>[14219.222516] radeon 0000:01:00.0:   SDMA0_STATUS_REG   = 0x46CEE557
>[14219.222518] radeon 0000:01:00.0:   SDMA1_STATUS_REG   = 0x46CEE557
>[14219.222520] radeon 0000:01:00.0:   CP_STAT = 0x00000000
>[14219.222522] radeon 0000:01:00.0:   CP_STALLED_STAT1 = 0x00000000
>[14219.222523] radeon 0000:01:00.0:   CP_STALLED_STAT2 = 0x00000000
>[14219.222525] radeon 0000:01:00.0:   CP_STALLED_STAT3 = 0x00000000
>[14219.222527] radeon 0000:01:00.0:   CP_CPF_BUSY_STAT = 0x00000000
>[14219.222529] radeon 0000:01:00.0:   CP_CPF_STALLED_STAT1 = 0x00000000
>[14219.222530] radeon 0000:01:00.0:   CP_CPF_STATUS = 0x00000000
>[14219.222532] radeon 0000:01:00.0:   CP_CPC_BUSY_STAT = 0x00000000
>[14219.222534] radeon 0000:01:00.0:   CP_CPC_STALLED_STAT1 = 0x00000000
>[14219.222536] radeon 0000:01:00.0:   CP_CPC_STATUS = 0x00000000
>[14219.222556] radeon 0000:01:00.0: GPU reset succeeded, trying to resume
>[14219.435458] [drm:ci_dpm_enable [radeon]] *ERROR* ci_start_dpm failed
[14219.435472] [drm:radeon_pm_resume [radeon]] *ERROR* radeon: dpm resume failed

**Comment by amarildojr** [comment]
@jeh72 Could you try an older firmware?

**Comment by jeh72** [comment]
Older firmware? As in Linux firmware blob for the gpu?

**Comment by amarildojr** [comment]
@jeh72 Exactly.

**Comment by amarildojr** [comment]
WELL WELL WELL...  I tested the oldest firmware available, linux-firmware 20130725-1, and the crashes don't happen. This is with current Arch, not a single package is old.

I'm hitting 10 to 30 FPS, but at least the crashes don't happen which is a very good sign of where the problem might be.

I'll report the firmware problem to AMD.

In the mean time, does anyone know how I can try running the firmware from Catalyst?

**Comment by Tele42** [comment]
@amarildojr, that firmware is from before the release date of your card's chipset. Is there any power management for your card with a firmware from that year? I wonder if passing ```radeon.dpm=0``` or maybe ```amdgpu.dpm=0``` to the kernel with newer firmware would prevent the crash.

**Comment by jeh72** [comment]
I tested with linux-firmware-20151207, and that made no difference with mesa-11.1.4 and llvm-3.5.  Still get the hang every 15 minutes or so.

**Comment by amarildojr** [comment]
@Tele42 I remember passing radeon.dpm=0 meant very reduced performance. Is that true these days as well?

**Comment by Tele42** [comment]
Yes, disabling reclocking on the gpu is expected to give low performance.

**Comment by amarildojr** [comment]
Just finished playing for +40 min without a single issue, with `radeon.dpm=0`. Could `si_dpm.c` (in the Kernel driver) be the problem?

**Comment by jeh72** [comment]
I should try that too with llvm 3.8 and Mesa 12. Although, there's a problem with that theory - the amdgpu driver has the same crashing issue. Do they share dpm code?

**Comment by amarildojr** [comment]
For all I can remember, RadeonSI and AMDGPU share most of the same code. And since this hang problemalso happens on AMDGPU I think you should try disabling DPM for it as well.

**Comment by jeh72** [comment]
I just tried the same thing.  Crashed for me.  I tried radeon.dpm=0, played two matches, and got no crashes.  Usually it crashes during the first match.  Performance was so bad that it was unplayable though.

What are the chances of this being yet another dpm bug?  The radeon driver has been broken so many times over the last few years that I'm seriously considering nvidia again, and I don't even like them...

**Comment by amarildojr** [comment]
I'm compiling my Kernel with a heavily modified patch for `si_dpm.c` [1] from the SteamOS Kernel. The file is at least 1 year old so I believe it's in a state where it could work with TF2.

Feel free to try it too: https://github.com/amarildojr/AMDGPU-Radeon-DPM/blob/master/tf2.patch

I don't think the problem is AMD, though, because the hang doesn't happen on the proprietary drivers. And since you'd be forced to use proprietary drivers for NVIDIA, it wouldn't make much sense changing vendors. In addition, AMD is much more OSS friendly, they're opensourcing tons of important technologies (like Vulkan, OpenCL, etc).

**Comment by jeh72** [comment]
I have nothing against radeon cards themselves (they are great in Windows), it's just the open source driver still being buggy years after I purchased my R9 290 is kind of tiring.  If amdgpu-pro worked perfectly with all distros and supported gpu switching I would change to that and never go back to the oss driver, but I digress..

Looking at that patch, aside from a lot of tab length and spacing adjustments, most of the other changes look like removing features.  I'm not that good at C, but are they removing a lot of power saving features here?

Also, what kernel versions will this patch work with?

**Comment by Tele42** [comment]
@amarildojr, so if I'm reading your patch right, you're hard wiring a voltage calculation for your specific card, removing VCE specific sections, and hitting si_parse_power_table(rdev) before r600_parse_extended_power_table(rdev). Is that correct?

**Comment by amarildojr** [comment]
@jeh72 You should try the OSS drivers for NVIDIA if you think AMD's is buggy hehehehe

@Tele42 I haven't completely read the patch, but you're right. I made no contribution to it myself, it's only a `git diff` between the `si_dpm.c` file from 4.7.2 and the SteamOS Kernel, and the file is at least 1 year old. I did this to see if older versions of `si_dpm.c` work, because if they do than we would've finally narrowed the problem down to DPM.

Do you think that intead of patching the current dpm file, I should just paste an old (3.16) `si_dpm.c` file into the 4.7.2 source dir? I'm new to this so I don't know if it will "just work".

**Comment by fixxxera** [comment]
I've got the same issue with 7790 with latest(actually all of them) radeon driver. I used to play it with Kubuntu KDE 16.04 with AMDGPU-PRO with no issues. Its without any problems with Catalyst in any distro.  Problem persists only with radeon/opensource AMDGPU drivers. In general for now i will stick with manjaro. They did a subsystem for Xorg so we can still use FGLRX(Catalyst) even with 4.7.3 kernel and all latest updates. So in that case Catalyst uses xorg 1.17 while the rest of the system goes with 1.18 and above. I hope TF2 devs fix that(im sure its them) or the AMDGPU-PRO comes available for all distros.

**Comment by Xylemon** [comment]
I can confirm on this freezing as well on my AMD and nVidia card. It seems to happen when using the (experimental) reclock support with the Nouveau drivers or using the new AMDGPU driver included with Linux. This is disappointing, I was expecting the game to preform better on AMD hardware but recently it's gotten more buggy and slower than ever. Out of sheer curiosity, I tried TF2 under Wine and while getting worse performance, the freezing does not happen. Unfortunately, it seems that the viable options are either:

- Get the proprietary drivers
- Play under Wine (which runs god awful)

Well, this sucks. I hope @amarildojr's findings can lead to some kind of proper fix. Perhaps the DPM issue should be reported on the bug tracker for AMDGPU driver: https://bugs.freedesktop.org/buglist.cgi?product=xorg&component=Driver%2FAMDgpu&resolution=---

**Comment by amarildojr** [comment]
I can't find the issue, sorry. Since DPM off means no crash, AMD developers should look into that. I'll comment something like that tomorrow, on the bug tracker.

**Comment by ThanosApostolou** [comment]
Same thing happens to me on my radeon HD 7750 with both TF2 and Dota 2. Tested with Ubuntu 16.04, Ubuntu 16.10 and Antergos.

**Comment by xtremyst** [comment]
Same problem with debian testing, I have a VGA ASUS RADEON R7 250 R7250-2GD5 2GB GDDR5 and game hangs after 10-15 minutes of playing. Also I'm using the open source drivers since proprietary drivers are not available in testing repos atm.

**Comment by amarildojr** [comment]
Just tried Mesa-Git (13.1) with the AMDGPU driver on R9 270X and the 4.9-wip Kernel. The crash happens here as well.

However, looking at journalctl I can see new errors from the AMDGPU driver, and a brief research tells me it could be some TF2 texturing problem.

The error: GPU fault detected: 147 0x000ac802

Similar bugs have been resolved already:

https://bugs.freedesktop.org/show_bug.cgi?id=87278
https://bugs.freedesktop.org/show_bug.cgi?id=84614

LLVM seems to be related too.

**Comment by amarildojr** [comment]
@xtremyst you can downgrade xorg to version 1.17.4 and use the proprietary drivers, they're in the debian snapshot (or similar name).

**Comment by xicronic** [comment]
Same issue, hangs system whether I'm fullscreen or windowed. I'm using Ubuntu 16.10 w/ an RX 480 on the padoka ppa for the latest Mesa. The game plays fine for 10-15 minutes before abruptly stopping, I had system monitor up in the background and RAM usage was normal. I don't have this issue on L4D2 or CS:GO.

**Comment by udvarit** [comment]
Hey everyone,

I get the same bug with my new RX 460 too. Ubuntu 16.10, AMDGPU driver, Mesa: 12.0.3, Kernel: 4.8.0-26-generic, LLVM 3.8.1. 
I was affected with my previous config too, AMD 7770, 16.04, latest everything from the official repos.

**Comment by udvarit** [comment]
Update: I get the issue with the AMDGPU-PRO driver too. I was really hoping that I won't get it because with fglrx I didn't get it either, but it looks like the Pro driver is not far enough from the AMDGPU driver in this regard.

**Comment by Eriner** [comment]
Valve, any comment on this issue? Has this been tested internally? This has now been a longstanding problem for users of free and open source drivers on radeonsi hardware. This issue only exists in TF2, and only existed after the update. With radeonsi now advertising OpenGL 4.5 compliance, now more than ever the open source drivers are in a position to be used in place of proprietary drivers.

I've been experiencing this issue since it's inception last year. I am (and have been) using mesa + radeonsi, on both an r9 280x and an rx 480. The r9 280x did not use AMDGPU, yet both devices are impacted by this issue. This rules AMDGPU out. Seeing as the issue only cropped up immediately after the update, and exists across various versions of mesa as reported by the other commentators, I ask that you set up a test environment and attempt to reproduce and debug the issue. Even if the issue is not in your code, but a mishandling of an API operation by mesa, I'm sure they would love to fix the issue. Based on the responses thus far, all reports suggest that the issue was introduced during the update to TF2.

With Valve's push for steam machines, Linux, and open source in general, fixing this issue and enabling people to use open source drivers with an AMD graphics card seems like a focus that fits the message. 

Mesa bugtracker: https://bugs.freedesktop.org/show_bug.cgi?id=93649

**Comment by jeh72** [comment]
I'm surprised to hear that this is an issue with amdgpu-pro now.  Maybe it all comes down to problems with dpm?

**Comment by udvarit** [comment]
@jeh72: In the end I gave in, installed Win7 and the latest drivers, and I still got that lockup. I'm not sure what to even believe anymore.

**Comment by amarildojr** [comment]
> In the end I gave in, installed Win7 and the latest drivers, and I still got that lockup. I'm not sure what to even believe anymore

WHAT???? Are you serious? :O

**Comment by BoctorPoo** [comment]
> @jeh72: In the end I gave in, installed Win7 and the latest drivers, and I still got that lockup. I'm not sure what to even believe anymore.

Good lord. Is dpm really this horrid for games, or is someone secretly lobbying for NVidia?

**Comment by xalalau** [comment]
> In the end I gave in, installed Win7 and the latest drivers, and I still got that lockup. I'm not sure what to even believe anymore.
Me too.

**Comment by JelloMonster118** [comment]
@udvarit I had to give in and install Win 10, but I didn't get lock ups with that.
Does Windows 7 have the right drivers with it or does your AMD card not support it?

i was using ubuntu, i have a r9 380. (but i dont think the card matters, its just the crappy open source drivers)

**Comment by Fornax** [comment]
I'm having these freezes too, with the HD7750 and the RX460 on Arch Linux.

**Comment by BMWDriver** [comment]
Serious crash also with R7 265 running on LinuxMint 18 (based on Ubuntu 16.10). Quite surprising to get such a hard crash with no other option but a 5 second power down push on the power button. The sound also crashes and does like a skipping cd until I press mute; it shuts the sound then nothing else seems to happen, even un-muting becomes dead.

**Comment by black2th** [comment]
Full system crash after 5 minutes or so of TF2. Screen freezes and sound loops and no response from any keyboard shortcut or anything. The only option for me is to either hold down power or hit reset. I'm running Ubuntu Gnome 16.04 with Padoka on a RX 470 GPU. This is literally the only game I play consistently, and I hate the idea of returning to Windows just to play a game that's so old. Is there anything else we can do to get this taken care of?

**Comment by dkulinski** [comment]
After the latest AMD driver update on Arch Linux I was able to play a full game of TF2 Payload without a lockup.  I'm wondering if this has resolved the issue.  I have not been able to test again but I haven't had a full game since I purchased this rig in early October.  I am running a Pentium G4400 and an AMD RX 460.

**Comment by jeh72** [comment]
By driver update, do you mean an amdgpu-pro update, a mesa update, or a kernel update?

**Comment by dkulinski** [comment]
This was the Open Source AMDGPU driver.  I have not installed the AMDGPU-PRO series driver.  

It was this package that updated on my Linux installation:
https://www.archlinux.org/packages/extra/x86_64/xf86-video-amdgpu/

Let me know if you require additional information.

**Comment by jeh72** [comment]
Rosco-
Thanks for that, although would that fix re-clocking being broken after the crash? With my R9 290 at least it gets stuck at the lowest power level possible after recovering from the long hang, ruining performance in tf2

**Comment by ElectricTriangle** [comment]
@dkulinski 

Unless you get a chance to test more, I would say it's not fixed. I've gone for several hours with no hang and open it another day and the game crashes in about 15 minutes (this is with radeonsi, but the situation is much the same.)

My specs for anyone who cares to know (and any Valve employee reading, unlikely as that may be).
https://gist.github.com/ElectricTriangle/96eab8d9837e338afa404351b656be9c

**Comment by dkulinski** [comment]
@ElectricTriangle this is good information.  Since I have had this rig, the dozen attempts I have tried to play TF2 have all hung within 4 to 10 minutes of starting, never any longer.  All attempts have been on Hoodoo.  I was very excited when it continued to run last night.  All my attempts have been with RadeonSI driver.

**Comment by amarildojr** [comment]
Tried it last night with the latest `xf86-video-amdgpu` and `mesa-git` and `llvm-svn`, with the latest `amd-staging-4.7` Kernel. Still hangeg.

**Comment by amarildojr** [comment]
And I can't recover at all, I have to hard reset my machine.

**Comment by bniels707** [comment]
Looks like other users on [this Reddit thread](https://www.reddit.com/r/linux_gaming/comments/5feykd/rx_480_users_can_you_play_csgo_soma_without/) are reporting similar issues with CS:GO and Soma.

**Comment by amarildojr** [comment]
Played for 1 hour last night with no problems, using Catalyst 15.12 on my R9 270X.

**Comment by ElectricTriangle** [comment]
> Played for 1 hour last night with no problems, using Catalyst 15.12 on my R9 270X.

As I mentioned on Mesa bugzilla, that doesn't do anything for me. So thanks but no thanks.

**Comment by BMWDriver** [comment]
Not sure if this is anything relevant, but on Windoze, with the same system I use under Linux, there is often a hang of about a fraction of a second to up to one or two seconds at about the same time period of an expected crash under Linux. Often that seems to happen specifically at kill time, either my avatar death or one of my kills, or when something graphically heavy is going on like crits coming my way or going from my weapons. Hard to be scientific though about these occurences.

**Comment by nayr1991** [comment]
Unfortunately, I have this same issue. I have played a handful of games of TF2 over the past 3 days and my machine has completely locked up after ~5mins each time.
In the thread that bniels707 linked, there is a theory on manually setting the power profile. I will give it a go and see.


Specs:
Arch
Kernel: 4.8.10-1-ARCH
xf86-video-amdgpu 1.2.0-1
CPU: Intel i5-6600K (4) @ 2.9GHz
GPU: AMD Radeon RX 470 8GB

**Comment by amarildojr** [comment]
This is an embarrassment for VALVe.

**Comment by Rosco-github** [comment]
No, this is an embarrassment for mesa.

**Comment by amarildojr** [comment]
We don't know if it's in mesa. What we DO know is that this problem appeared after the mentioned update by VALVe.

**Comment by ElectricTriangle** [comment]
> No, this is an embarrassment for mesa.

A similar hang also occurs when using catalyst. No need to blast Mesa for TF2's broken game code.

**Comment by nayr1991** [comment]
Is running the Windows version in wine still an option? Is it likely to be any different to the native linux version?

**Comment by BoctorPoo** [comment]
> A similar hang also occurs when using the proprietary drivers. No need to blast Mesa for TF2's broken game code.

Valve is most likely outsourcing a lot of their "SteamOS®" and OS X development on a contract basis, especially ToGL. I won't be surprised if this bug lives to be more than a year old.

**Comment by amarildojr** [comment]
@nayr1991 It's more than likely that it'll work fine. You could try it.

@BoctorPoo VALVe doesn't care about Linux anymore. They only started the SteamForLinux and SteamOS projects "just in case" something happens on Windows, because Microsoft was really ready to screw developers' arses at that time.
If VALVe *REALLY* cared about Linux, we wouldn't have this bug at all.

**Comment by BoctorPoo** [comment]
They never did care to begin with, though. I'm almost certain it's contractors. Same with the OS X port, which is why voice chat has been "varying levels of broken" on it for about 2 years now.
I have to use a different brand of video card just to play the game without Windows. Or I did when I played.

**Comment by bniels707** [comment]
As far as I know AMDGPU and AMDGPU-PRO both use the same amdgpu-drm kernel code which handles everything but the userspace OpenGL, OpenCL, and Vulkan parts, so it's entirely possible both would show the issue.

**Comment by stevethepocket** [comment]
> Not sure if this is anything relevant, but on Windoze, with the same system I use under Linux, there is often a hang of about a fraction of a second to up to one or two seconds at about the same time period of an expected crash under Linux. Often that seems to happen specifically at kill time, either my avatar death or one of my kills, or when something graphically heavy is going on like crits coming my way or going from my weapons. Hard to be scientific though about these occurences.

I'd say this is _very_ relevant. It makes it sound like there's something bugged with the engine itself, and that either Windows or the Windows driver has some kind of error handling thing that lets the system keep chugging along in spite of it.

This is a client-side bug, so it should be reproducible by playing back demo files. Theoretically someone who has both versions of the game could record a lengthy session in Windows where such a hang occurs, then play it back on the Linux version to see if it crashes at that same point. And then email the demo file to Valve with notes so they could run a trace on it or something.

**Comment by BoctorPoo** [comment]
> I'd say this is very relevant. It makes it sound like there's something bugged with the engine itself, and that either Windows or the Windows driver has some kind of error handling thing that lets the system keep chugging along in spite of it.

You're probably correct. I had lots of unusual hanging in the middle of games when I played with an ASUS R9 380 (4GB) under Windows 7 Enterprise amd64. What you said about the demo files is ingenious, I have no idea how I hadn't thought to try that yet.

>Valve cared enough to make SteamOS, but it probably is not a big hit, so they either push something new out or abandon it eventually.

Isn't SteamOS mostly Debian Stable with some defaults changed, different branding, and some new repos for proprietary video drivers? I'm not sure if Valve would work together with AMD. A lot of their sanctioned Steam Machines ship with GTX 900-series GPUs.

**Comment by amarildojr** [comment]
@bniels707 Some users reported it doesn't happen on AMDGPU-PRO.

@stevethepocket I also thought about this. Both on Windows and Linux using the proprietary driver, there seems to happen a very quick hang, but it's not as long as previously reported. To me it's 1/10 of a second on both platforms.
And while using the FOSS drivers, it doesn't happen too soon if there are few players on the servers. I noticed it happens quicker when there are lots of engineers.

**Comment by amarildojr** [comment]
OH MY LOOOORD!!!!!!!

Been playing for ~25 mins without crashes!! I believe this commit fixed the hangs https://cgit.freedesktop.org/mesa/mesa/commit/?id=6dc96de303290e8d1fc294da478c4f370be98dea

I'll test for way longer just to confirm.

**Comment by amarildojr** [comment]
45 minutes, not a single crash. I believe it's fixed.

**Comment by amarildojr** [comment]
Played 2 sessions of 1 hour each, no hangs at all.
To me, this is fixed.

**Comment by BoctorPoo** [comment]
> To me, this is fixed.
Do you mind telling me which kernel/distro/GPU this test was under? I might test on my R9 380 with it, now. This will be an extremely useful commit if I no longer need the darned Nvidia blobs to play Source on GNU/Linux.

**Comment by amarildojr** [comment]
Yup, it was very useful. Michael Danzer said it was present for 9 years :P

Software:

Arch Linux
Kernel: amd-staging-4.7
Kernel Driver: amdgpu
mesa-git
llvm-svn

GPU: Sapphire R9 270X

**Comment by jeh72** [comment]
I'm thrilled to see that this issue (and maybe some with other games as well, like xcom) might be fixed.  If this commit does the trick, which mesa version will this commit be part of?  12.0.x?

I'm going to have to fire up my gentoo HDD and test this with my R9 290.

**Comment by ElectricTriangle** [comment]
It needs more testing, but I'll certainly be doing this soon. The game can have far longer periods between crashes.

**Comment by amarildojr** [comment]
@jeh72 Didn't mesa 12 reach it's EOL? I don't know if they're still backporting fixes.

**Comment by amarildojr** [comment]
Update: One RX480 user confirmed it's fixed for him.
https://bugs.freedesktop.org/show_bug.cgi?id=93649#c72

**Comment by jeh72** [comment]
@amarildojr I don't follow mesa versions that closely anymore, but the patch is so minimal that it may work with any recent version of mesa.  I will have to try it with gentoo (I have 13.0.2 ready to be installed there)

**Comment by amarildojr** [comment]
@jeh72 No problem. Just remember to actually patch the file if you're not building from GIT, otherwise it won't work.

**Comment by jangoknight7** [comment]
Can someone explain how to apply the fix for those coming from google?

**Comment by amarildojr** [comment]
@jangoknight7 What distro are you using?  And what version of mesa?

**Comment by jangoknight7** [comment]
@amarildojr I'm using Ubuntu with Mesa 11.2.0-devel

**Comment by amarildojr** [comment]
@jangoknight7 You could simply use padoka PPA for mesa-git and llvm-svn, because the fix is already there :)

By Ubuntu you mean 16.04?

**Comment by jangoknight7** [comment]
@amarildojr Ah, nice. I didn't expect the fix to be published already. And I'm actually stuck on Ubuntu 15.04 because my system is fucked

**Comment by amarildojr** [comment]
@jangoknight7 I believe you can use padoka's PPA on 15.04 as well, but you must be familiar with adding and removing PPA's if something goes wrong.

Otherwise you'll either have to learn how to get the sources for your package and then re-compile them. It's pretty easy, actually, search Google for "Ubuntu rebuilding packages", the tutorials teach how to apply patches as well.

**Comment by ElectricTriangle** [comment]
@amarildojr 
I don't think that's in the padoka PPA just yet. The change was committed on the 7th and the last build in Padoka was on the 6th.

**Comment by nayr1991** [comment]
@amarildojr Did you use mesa-git from the AUR and just add that patch to prepare()?
I've just tried this and it hasn't seemed to fix my issues.

**Comment by jangoknight7** [comment]
@ElectricTriangle It's not, I tried it
@amarildojr Can you post specific instructions on how to apply the patch and install it?

**Comment by ElectricTriangle** [comment]
@jangoknight7 
It doesn't actually work, don't bother. Amarildo is just ready to jump on any potential "fix" without doing enough testing. I applied the patch manually and it still crashed.

**Comment by amarildojr** [comment]
@ElectricTriangle Too bad, I thought he used to build everyday. Some users complain he has 6-weeks-old LLVM. Maybe "oibaf" PPA is more recent?

@nayr1991 No, I have the repos for mesa-git and llvm-svn. They're built every 6 hours :D

@jangoknight7 https://www.cyberciti.biz/faq/rebuilding-ubuntu-debian-linux-binary-package/

@ElectricTriangle Maybe you need mesa-git and llmv-svn for it to work? Also, look at the source dir/file to see if the patch was correctly applied.

**Comment by amarildojr** [comment]
For those using mesa older than 13: you won't get the fix unless you re-compile from source or grab a package that was re-built for your distro, because mesa-12 will NOT see any more point releases unfortunately. And even if you manage to do so, I don't think the patch will work unless you have LLVM-SVN and mesa-git.

**Comment by ElectricTriangle** [comment]
Well I'm willing to admit when I'm wrong, I only built/installed the 64-bit drivers. I'm installing from obiaf PPA right now, I'll see if it actually works.

**Comment by amarildojr** [comment]
As long as oibaf's PPA is up-to-date and he's correctly building mesa, you should be OK.

**Comment by Lukypie** [comment]
Seriously? Is that fixed? Just a line of code? 
Rofl, seems like I can close the issue then. But I'm really angry against steam developers. 
Not with the AMD/Mesa ones.

**Comment by amarildojr** [comment]
To be fair, nobody is to blame. This bug wasn't triggered for 9 years, I guess that's how sampler states were dealt with in the past. Then VALVe and a few other games used a new method of texture streaming and it wasn't compatible with what mesa had been doing for these 9 years.

**Comment by jeh72** [comment]
I played two matches of tf2 without issue this morning.  Usually I crash during the first one.  It's not conclusive yet but it's looking good.  I also played a mission of XCOM with no crashes, but I think that game can take even longer to crash.

@ElectricTriangle if you didn't install the 32bit drivers, you didn't get the fix while running the game:

> $ file hl2_linux
hl2_linux: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 3.2.32, BuildID[sha1]=817971d228a59319b6e0296084d041a814675cc4, not stripped

**Comment by ElectricTriangle** [comment]
@jeh72 
Correct. I had forgotten to do that, as I mentioned in my earlier comment.

**Comment by jeh72** [comment]
This morning I was using live builds of mesa and llvm in Gentoo.  I'm going to try llvm-3.9 and manually patching mesa 13.0.2.  I'll also take a look at mesa 12 source to see if the patch fits easily there too.

**Comment by jeh72** [comment]
Patch applies cleanly to mesa 12.0.4 and 13.0.2.  It is just one more line of code, after all :p

**Comment by ElectricTriangle** [comment]
I'm reasonably certain that the patch fixed things. It still probably needs more testing, but I had a three-hour and four-hour play session without any issues.

**Comment by lex93ushakov** [comment]
https://cgit.freedesktop.org/mesa/mesa/commit/?id=6dc96de303290e8d1fc294da478c4f370be98dea?

**Comment by jeh72** [comment]
Just did some more playing this morning with my patched 13.0.2 on Gentoo.  So far so good.  I guess as soon as a mesa version is released with this patch, this issue can finally be closed.

**Comment by stevethepocket** [comment]
Are there any downsides to this only being fixed in future Mesa releases? Any entire series of hardware that are ineligible for it, for example, or current-gen distros that won't automatically download the update? I have no idea how this sort of thing is handled.

Also, I'd still like to see some investigation into whatever the game's doing to trigger this, because if it's the same thing that's causing minor hiccups in Windows, it's probably still a legit bug that's worth bringing to Valve's attention; it's possible that fixing it will head off some potential problems down the line.

**Comment by Lukypie** [comment]
It depends by the distros maintainers, something like arch linux may receive this fix quicker than debian or ubuntu because they rely on the cutting edge versions of mesa.
I think you can contact the mesa package maintainers for debian or ubuntu to ask to apply this fix quicker, this should work even for older versions of mesa.

**Comment by amarildojr** [comment]
Well, I had to ditch Arch and mesa-git because I no longer have a mouse cursor there. I don't know what is the cause of the bug, so I'm on Ubuntu with the AMDGPU-PRO stack for now, which is OSS Kernel driver + Proprietary userspace OGL/OCL/etc where this bug is not present, thanks to Zeus.

@stevethepocket No downsides as far as I'm concerned.

**Comment by nayr1991** [comment]
mesa-git and lib32-mesa-git from http://pkgbuild.com/~lcarlier/$repo/$arch seems to have resolved the crashing issue for me.
I've played a few games since updating and have not had any issues.

**Comment by cgameing** [comment]
The link appears to be broken, does anyone have a solution to this,
Im on linux 4.7 and the issue still persists

**Comment by ElectricTriangle** [comment]
@csgameing
If you want the issue fixed, you need to set up and use a recent version of
Mesa from a repo such as
https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers (just set up
the repo and upgrade as usual)

**Comment by BoctorPoo** [comment]
I tried the Oibaf PPA's graphics stack with Ubuntu GNOME 16.04 and my Radeon R9 380 STRIX (Asus, 4GB Video RAM). It's.. sort of fixed. The game froze completely, similar to before, and I could not alt+tab out of it. However, I'm sure the latter is GNOME's fault, because I could still move the cursor, adjust my volume, and toggle caps/numlock, etc. The OS and kernel themselves were fine. Either way, this is big progress.

**Comment by ElectricTriangle** [comment]
@BoctorPoo 
Assuming you added the PPA and upgraded the 32-bit drivers, it sounds like you may be running into a different problem.

**Comment by Rosco-github** [comment]
I was able to play 10-15 games without problem using mesa-git on manjaro but TF2 eventually hanged like before forcing me to reset. Same symptoms except that there was nothing in the logs.

**Comment by BoctorPoo** [comment]
> Assuming you added the PPA and upgraded the 32-bit drivers, it sounds like you may be running into a different problem.

Yeah, I'm almost certain it's not the same one.

**Comment by amarildojr** [comment]
@Rosco-github Make sure to have "lib32-mesa-libgl-git" installed.

**Comment by cgameing** [comment]
E: Unable to locate package ib32-mesa-libgl-git

What ppa is that from

**Comment by cgameing** [comment]
I cant figure how to install lib32-mesa-libgl-git
Do i have to apply a patch?
Im a noob at installing anything on linux without apt-get or snap

**Comment by ElectricTriangle** [comment]
@cgameing 
There is no "lib32-mesa-libgl-git".
What you need to do is to add the https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers repo (instructions on page), and then upgrade all the packages on your system. You'll want to remove the repo after a new version of Mesa is out though, since it always contains the newest version of Mesa it can have frequent breakage.

Alternatively, wait for a new version of Mesa greater than 13.0.1 to be released and then upgrade to it.

**Comment by amarildojr** [comment]
@ElectricTriangle Yes there is.

>[amarildo@amarildo ~]$ pacman -Qs lib32-mesa-libgl-git
local/lib32-mesa-libgl-git 87542.8801734da7-1 (mesagit)
    Mesa 3-D graphics library (32-bit) (git version)

I believe it's not called that in Padoka's PPA, though.

**Comment by whitephoenix0** [comment]
This happened to me on both xubuntu 16.04 and arch with an R9 280. I believe fglrx made it work before, but since that no longer functions with xorg I guess we're out of luck for now.

**Comment by ElectricTriangle** [comment]
@whitephoenix0 
The bug has been resolved, you should read through the most recent comments to learn how to upgrade to a version of Mesa with the fix.

**Comment by kisak-valve** [comment]
Closing as fixed in [Mesa 13.0.3](https://lists.freedesktop.org/archives/mesa-announce/2017-January/000283.html). Please update to this version or newer if you are experiencing this issue.

**Comment by vpltd-peterm** [comment]
This thread is dreadful. I see a pile of hate on Valve here for what is, at the end of the day, a Mesa bug. If your system locks up because of what an OpenGL app is doing - it is a driver bug, end of discussion.

As you can now see, the bug was indeed in Mesa and has been fixed. Kudos to the Mesa guys. Some of you really want to think about your behaviour towards Linux game developers though, if you want continued support...

**Comment by BMWDriver** [comment]
I disagree. Everybody has been respectful in spite of some obvious frustation, which I would think is legitimate. I saw no slander nor anything out of hand here. It's really difficult to point to what since drivers and software are closely intertwined, so I'd say this has been a great place to figure this out. 

If anything, this frustrtion speaks loudly for how much people appreciate the game and the Linux platform and everything involved, in wanting to see it all work. And that is probably a great compliment to those developers.

Some resort to emotional blackmail when they say things, in a desperate move that perhaps will make things go forward the way they would like it to, and being that they are completely powerless other than to voice their frustation. But they are ultimately allowed to dislike and go elsewhere. That is a common thing.

This has been a very respectful thread.

**Comment by ElectricTriangle** [comment]
@vpltd-peterm 
Is support not part of your job? You seem to be a developer, so allow me to express the problem.
If I pay for a game, I deserve a response from the developers/porters when I tell them it's broken (and indeed I have gotten them from every other game company save Valve). This bug was open for over a year with absolutely no responses from the TF team through email or on this github page (though fortunately with the recent appearance of Kisak this repo is being actively maintained again). However, if the team had communicated with the community and the mesa devs this would have likely been solved very quickly.

**Comment by stevethepocket** [comment]
It's especially valid because Linux is open source, and Valve could totally dig into the Mesa code and try to diagnose the problem themselves. That's something I'm always hearing from the Linux community, that if something's not working you should learn to code and fix it yourself. Which is a really arrogant attitude to have, mind you, but it highlights the spirit of collaboration that the platform is built on. One of the great things about Valve getting involved with Linux is that we finally have a real AAA game developer again (for the first time since Id dropped their Linux team) that can contribute their own expertise to a component of the platform that's often neglected — namely anything to do with graphics. And we're already seeing that with the Vulkan project. But when it comes to anything to do with games other than Dota 2, it seems they can't be bothered.

**Comment by vpltd-peterm** [comment]
I can name names and post numbers if i have to, but to be honest that is obvious for anyone who reads the whole thread.

We had similar responses when it turned out our ports of Overlord 1 & 2 triggered similar machine crashes, so I know first hand the type of responses and attitudes being found here.

**Comment by vpltd-peterm** [comment]
@ElectricTriangle even with support from the developer, bugs in mesa do not always get resolved quickly. We provided Marek and Nicolai with free copies of Overlord and steps to reproduce the issues being seen, yet it still took a while for the problem to get found and solved. In the meantime we received much "praise"  for "releasing a buggy game" and "not supporting mesa".

Similarly, the black LOD switching issue in Witcher 2 has just been solved (by Marek again, awesome guy!), and despite the fact that this problem did not occur on either the nvidia driver, fglrx, OR on any of the Mac's GPU's, the blame was squarely landed on us.

**Comment by vpltd-peterm** [comment]
Mesa being open source is neither here nor there. Driver development is a very specific kind of development. Simply assuming that because the source code is available, game developers can get in there and find the driver bugs is not valid.

**Comment by jeh72** [comment]
Guys I don't think the fix is included in mesa-13.0.3.  I just checked the source from Fedora's mesa-13.0.3 src rpm and the if statement is missing.

**Comment by dankegel** [comment]
True, but app developers *can* get in there and find/fix driver bugs.  Happened here this week (at a startup that sells an appliance that uses opengl): https://bugs.freedesktop.org/show_bug.cgi?id=99451
Having your company depend on graphics not crashing is a powerful motivator.

**Comment by JamesTheAwesomeDude** [comment]
@Lukypie Upgrade your kernel, upgrade mesa, and DON'T use the AMDGPU driver or FGLRX; use Radeon.

I used to get this bug and a few other CS:GO+TF2 hangs like yours, but it's all fixed by that.

**Comment by Lukypie** [comment]
@JamesTheAwesomeDude sorry for the late reply but this problem was fixed by the recent builds of mesa

**Comment by dankegel** [comment]
cool.  For what it's worth, on Ubuntu 16.04, I've been using the preview builds of mesa 13
at ppa:ubuntu-x-swat/updates.   Casual users should just wait for Ubuntu 17.04, though, which will have mesa 17.

**Comment by cgameing** [comment]
on ubuntu 17.04 :( still getting them system freezes though

**Comment by kisak-valve** [comment]
Hello @cgameing, if it's a whole system freeze like this issue report, then you should contact your driver vendor. If your desktop remains interactive and you can alt-tab to the desktop or other application, then please open a new issue report so that we can investigate further.

**Comment by victoredwardocallaghan** [comment]
@vpltd-peterm if you are channeling all issues reported just to AMD committers and not the wider community then you should expect a higher latency for fix turn around. May I suggest taking one of us aside on the IRC or off-ml and provide the copy+instructions so other developers can handle the problem or at least try to. I say this because I noticed (have the impression of) a more bias towards some high profile committers seemingly being more in the know about current issues than other developers such as myself who don't directly work for AMD. Just something to keep in mind.

I think the core issue for Valve and this issue tracker is that problem details are completely drowned out by the sheer amount of traffic of users saying "me too".

**Comment by cgameing** [comment]
Sorry, for adding more voices to the traffic, I have posted the issue on a fourm for amd, and I should mention that this isnt something valve can fix, sorry if i have wasted anyones time.
