### ISSUE TITLE
[TF2] tf_use_match_hud 0 not being fully removed.

### ISSUE THREAD

**Issue by fearts** [ValveSoftware/Source-1-Games#2542]
If you set tf_use_match_hud 0 and then restart the game and join a server there will still be a blank bar at the top of your screen. The only way to remove this is to set tf_use_match_hud 1 and then back to 0 every time you want to play TF2.
![qwdwdqdwqd](https://user-images.githubusercontent.com/18254890/38068319-91e9573c-32de-11e8-8143-2e5382206f12.png)

**Comment by agrastiOs** [comment]
Fixed now, just tested.

**Comment by agrastiOs** [comment]
@kisak-valve

**Comment by kisak-valve** [comment]
Thanks, closing per the last couple comments.

**Comment by fearts** [comment]
@kisak-valve 

This issue is not fixed. Either the above user is trolling or doesn't understand the issue I posted here.

**Comment by agrastiOs** [comment]
@fearts Strange, I did the exact steps you mentioned and didn't manage to reproduce the issue.

**Comment by redpizza** [comment]
I knew Valve will never fix this :)

**Comment by agrastiOs** [comment]
@redpizza Write them a detailed and polite e-mail reporting the bug. TF Team seems to respond to emails more. I got a 4 year old big bug fixed by reporting it in email.

**Comment by Aepoh** [comment]
Still not fixed. Will never be fixed.
