### ISSUE TITLE
Crash when use microphone

### ISSUE THREAD

**Issue by SGmuwa** [ValveSoftware/Source-1-Games#3740]
On Kubuntu 21.10 (Ubuntu 21.10) Counter-Strike: Source when I activate a microphone on a server with players then game crash. The game works fine if a microphone is not turne on (do not press a microphone activation button). I can hear other players and all sounds, but I cannot speak. TF2 works fine.

logs from steam process:
```
src/tcmalloc.cc:278] Attempt to free invalid pointer 0x25e62230 
ERROR: ld.so: object '/home/pavel/.steam/debian-installation/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20211206210746_3.dmp[4522]: Uploading dump (out-of-process)
/tmp/dumps/crash_20211206210746_3.dmp
/home/pavel/.steam/debian-installation/steamapps/common/Counter-Strike Source/hl2.sh: line 72:  4423 Aborted                 (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
crash_20211206210746_3.dmp[4522]: Finished uploading minidump (out-of-process): success = yes
crash_20211206210746_3.dmp[4522]: response: Discarded=1
crash_20211206210746_3.dmp[4522]: file ''/tmp/dumps/crash_20211206210746_3.dmp'', upload yes: ''Discarded=1''
pid 4522 != 4521, skipping destruction (fork without exec?)
(process:4436): GLib-GObject-CRITICAL **: 21:07:48.121: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

crash_20211206210746_3.dmp: [crash_20211206210746_3.zip](https://github.com/ValveSoftware/Source-1-Games/files/7662385/crash_20211206210746_3.zip)

libc:
```bash
$ LC_ALL=C apt list --installed 2>/dev/null | grep -E libc\\W
klibc-utils/impish,now 2.0.8-6.1ubuntu2 amd64 [installed,automatic]
libc-bin/impish,now 2.34-0ubuntu3 amd64 [installed,automatic]
libklibc/impish,now 2.0.8-6.1ubuntu2 amd64 [installed,automatic]
```

Operating System: Kubuntu 21.10
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-22-generic (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i3-9100F CPU @ 3.60GHz
Memory: 15.5 GiB of RAM
Graphics Processor: AMD RV635

**Comment by SGmuwa** [comment]
Probabli dublicate: https://github.com/ValveSoftware/Source-1-Games/issues/3729

**Comment by gg-eorge** [comment]
I was having the same issue while running Day of Defeat: Source. Game runs perfectly fine but activating my microphone caused an immediate crash. I really don't know much about linux or anything but after pulling my hair out for a few hours I figured out how to fix it for me at least. It worked great before I installed lutris, so I purged lutris and all the packages it installed and my microphone started working again.

**Comment by pawel66031** [comment]
The same issue I have with Team Fortress 2. Before upgrading Ubuntu to 21.10, I could use microphone input during game without any problems. But after some software updates running `+voicerecord` in console or by binding to some key causes TF2 to instantly crash. Even in voice options clicking on Test microphone crashes instantly. I can hear some voices in voice-chat, but I can't trigger my microphone input. In order to fix that I tried to reinstall game with no success, still crashes. 

I tried to find solutions in this [mentioned issue](https://github.com/ValveSoftware/steam-for-linux/issues/1853), but I didn't find any solutions.

My PC specs:
```
OS: Ubuntu Jammy Jellyfish (development branch) x86_64
Kernel: Linux 5.15.0-25-generic
CPU: Intel i5-3450 (4) @ 3.500GHz
GPU: NVIDIA GeForce GTX 570 Rev. 2

Steam version: 1647446817
Pulseaudio version: 15.99
```
Any helps? I tried to search whole Internet in order to fix that small issue...

**Comment by robobenklein** [comment]
Also having this issue in TF2

```
src/tcmalloc.cc:278] Attempt to free invalid pointer 0x5422c1e0 
ERROR: ld.so: object '/home/robo/.steam/debian-installation/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20220409104552_3.dmp[1173952]: Uploading dump (out-of-process)
/tmp/dumps/crash_20220409104552_3.dmp
/mnt/stor/s/SteamLibrary/steamapps/common/Team Fortress 2/hl2.sh: line 72: 1172561 Aborted                 (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
```

Appears to happen 100% of the time in servers that have the convar set: `sv_voicecodec vaudio_celt_high`, on those where it's "steam" I do not have this issue.

**Comment by pawel66031** [comment]
I tried to change value in convar `sv_voicecodec` in my own server, where default I have is `vaudio_celt`. Setting that convar to `steam` actually works. It's a very strange problem that "vaudio_celt" codec can cause game crash.

**Comment by davidstaudt** [comment]
Anectodally, workaround for me (Ubuntu 21.x/22.04) was to disable 'Boost Microphone Gain' under Options/Voice (voice_maxgain "1")

**Comment by PhilArmstrong** [comment]
Same, CrashID=bp-f5f8ac07-03d7-48aa-a795-eeb282220822  is a typical example.

Turning off “Boost Microphone Gain” doesn’t seem to make any difference.

**Comment by PhilArmstrong** [comment]
Here’s a bunch of assert + crash dmp files from today.

[crash_assert_dmps.tar.gz](https://github.com/ValveSoftware/Source-1-Games/files/9397521/crash_assert_dmps.tar.gz)

**Comment by DanceMore** [comment]
I hit this recently (hello from Uncletopia us-west 🚀 ) and I think I've read everything I can on Github Issues and Reddit posts and hit the limits of my debugging ability.

I upgraded to `pipewire` because people were blaming `pulseaudio` bugs, but the issue still exists under `pipewire`. amusingly, the `pipewire` upgrade seemed trivial and works out of the box with most everything I've tested so far (Discord, `gqrx`, VLC, Chrome browser Youtube).

I am still suspicious of `libc6`, I upgraded to `2.34` in Debian Unstable and I distrust `libc` due to the recent EAC / DT_HASH issues and history of breaking applications in subtle ways.

honestly, since `pipewire` is giving me the smoothest Linux sound experience of my life, my personal workaround might just be to `unbind` my TF2 microphone key and wait patiently for a fix.

**Comment by surf51** [comment]
This issue is present on Steam Deck running SteamOS. Tested and it crashes on Counter-Strike: Source using the sv_voicecodec "vaudio_celt"

**Comment by yllekz** [comment]
This is happening to me on Linux Mint.

**Comment by DanceMore** [comment]
it never occurred to me in the past to check `cvarlist` and actually verify what the settings were server-side while I was experiencing the problem 🤦‍♂️ 

my experience with the bug has ended ""recently"", but I think it's due to Uncletopia setting to `sv_voicecodec 0` which I think is the classic Speex codec.

I will report back in if the bug returns. also you will want to run `cvarlist` filtered, it spits out 3500 lines but you can only scroll back a small portion of it. `cvarlist sv_voice` will spit out the 2 settings matching `sv_voice*`.

**Comment by cynidecia** [comment]
Can confirm this still happens on Linux Mint when `vaudio_celt_high` is set.

**Comment by Brokio** [comment]
This is happening on Steam Deck with some servers that use newer voice codec in Source games

**Comment by PhilArmstrong** [comment]
I am holding out hope that the forthcoming new release of TF2 built on the latest Linux runtime will fix this issue!

**Comment by XeemPad** [comment]
> I am holding out hope that the forthcoming new release of TF2 built on the latest Linux runtime will fix this issue!

Meanwhile CSS: 💀

**Comment by pavlokozlenko** [comment]
Valve forgot about linux players and steam deck.

**Comment by DosMike** [comment]
I'm crashing on a community server since the latest TF2 update (or a system update since ig) as soon as I hit +voicerecord. It crashes so hard that even steam dies. sv_voicecodec on the server is steam, I'm running Linux Mint 21.3 with PipeWire.
libc: 2.35-0ubuntu3.8
pipewire: 0.3.48-1ubuntu3
(I was looking for crash dumps but couldn't find any, dunno if I need to do anything special)

**Comment by JosSamLoh** [comment]
Changing **Client Beta Participation** from `Steam Beta Update` to `No beta chosen` fixed the crashing when using +voicerecord for me.

On **Fedora 41**
```
pipewire.i686   1.2.7-1.fc41
pipewire.x86_64 1.2.7-1.fc41
```

Fix found here: https://steamcommunity.com/app/440/discussions/0/601891467285269172/

**Comment by mirrorcult** [comment]
can confirm that opting out of the client beta fixed the issue for me -- i had the same issue where it crashes steam as well, even on `sv_voicecodec` steam servers. might be a separate recent regression

**Comment by pavlokozlenko** [comment]
I don`t use beta client

**Comment by DosMike** [comment]
thanks @mirrorcult that helped me at least :)

**Comment by AudioEmu** [comment]
Issue appeared for me a few days ago on Linux Mint 22 Kernel version 6.8.0-50

It happens on official servers with sv_voicecodec set to steam. I got excited to try again when I saw the game updated this morning but still crashing as soon as I key up :(

**Comment by AudioEmu** [comment]
Updating to say I just clicked "Test microphone" in the game's settings on the main menu and still had the issue there, so this has nothing to do with server codec it appears

**Comment by 0xVZ** [comment]
I found the solution!
[I found the solution on this forum](https://forums.linuxmint.com/viewtopic.php?p=1633095#p1633095)

It was pulseaudio, now the mic works, but the sounds of the game have a little delay or pop.
MAKE SURE TO RESTART THE PC AFTER, IT WILL NOT WORK WITHOUT A RESTART.

**Comment by pavlokozlenko** [comment]
> I found the solution! [I found the solution on this forum](https://forums.linuxmint.com/viewtopic.php?p=1633095#p1633095)
> 
> It was pulseaudio, now the mic works, but the sounds of the game have a little delay or pop. MAKE SURE TO RESTART THE PC AFTER, IT WILL NOT WORK WITHOUT A RESTART.

I use pulseaudio too

**Comment by 8of** [comment]
Fixed in latest Steam Deck beta update (released today) for me.

From https://www.steamdeck.com/en/news
```
Steam Deck Beta Client Update: December 20th
Note: this beta was re-released on 12/30 with a fix for crashes in games using Steam P2P Voice Chat on Linux.
```

**Comment by kisak-valve** [comment]
Counterstrike:Source Voice Chat bug and fix

Issue transferred from https://github.com/ValveSoftware/Source-1-Games/issues/6946.
@mandle420 posted on 2025-01-14T05:08:42:

#### Your system information
* Steam client version (build number or date): multiple
* Distribution (e.g. Ubuntu): arch(but also multiple)
* Opted into Steam client beta?: [Yes/No]no
* Have you checked for system updates?: [Yes/No]see above
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] no need fix is also described here
* GPU: Nvidia or AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
when pressing the voice chat bind, the game crashes.


#### Steps for reproducing this issue:

1. press the voice chat button in game.
2. 
3. 

To fix:
deb/buntu's 
```sudo apt install lib32-gperftools```
might be called something different haven't used deb based in a while

Arch 
```yay -Syu lib32-gperftools```

```cp /usr/lib32/libtcmalloc_minimal.so.4.5.16 ~/.local/share/Steam/steamapps/common/Counter-Strike\ Source/bin/libtcmalloc_minimal.so.4```

Change ~/.local/share/Steam to /locationofsteamlibrary/SteamLibrary/ if installed on a different drive.

**Comment by mandle420** [comment]
just keep in mind, that the version you copy, may be different, so if a copy paste on the cp command doesn't work, that's probably why. Either 

```ls /usr/lib32/libtcmalloc_minimal.*```

or bash complete if you've got it installed. the destination doesn't change.
also, the .so and the .so.4 files in usr/lib32 are symlinks, so you need to copy the file that has the whole version number.

**Comment by interrupt-routine** [comment]
I had the same issue on Ubuntu 24.04 LTS, Steam installed via snap. Using the microphone in Team Fortress 2 would instantly crash the game.

I managed to fix it by combining those [two](https://steamcommunity.com/app/221410/discussions/0/864971287695229512/#c864971287701590387) [answers](https://steamcommunity.com/discussions/forum/11/4691153988130290400/#c524225618711209848):

Connect the Steam snap to the audio-record plug:
```
 sudo snap connect steam:audio-record :audio-record 
```

In the Steam client, navigate to `Steam/Settings/Voice/Voice Input Device` and select your device in the dropdown menu instead of `Default`.

**Comment by ldh174** [comment]
> Replying to https://github.com/ValveSoftware/Source-1-Games/issues/3740#issuecomment-2589935571

#### For the ubuntu 24.04 users that are having issues and this did not fix the problem I may have a solution. 

##### Download a 32-bit library from an older Ubuntu release (Ubuntu 24.04 doesn’t include the 32‑bit library in its repos so apt can't find it):
`wget http://mirrors.edge.kernel.org/ubuntu/pool/main/g/google-perftools/libtcmalloc-minimal4_2.5-2.2ubuntu3_i386.deb -O libtcmalloc-i386.deb`

##### Unpack it:
`dpkg -x libtcmalloc-minimal4_2.5-2.2ubuntu3_i386.deb unpack/`

##### Copy the versioned .so file to your css bin/ folder:
`cp unpack/usr/lib/i386-linux-gnu/libtcmalloc_minimal.so.4.3.0 "/path/to/your/CS-S/bin/libtcmalloc_minimal.so.4"
chmod 644 "/path/to/your/CS-S/bin/libtcmalloc_minimal.so.4"`

##### Replace `/path/to/your/CS-S/bin` with the correct folder for your Steam library. Launch css and it should be working.
