### ISSUE TITLE
[CS:S] CT - SAS skin- tossing weapons is bugged

### ISSUE THREAD

**Issue by Brand0nnnnn** [ValveSoftware/Source-1-Games#3786]
If on CT team and with SAS skin selected, if you toss guns the guns travel less distance then if you select any other skin. This is not working as intended.

Here's a video thats shows this issue.
https://www.youtube.com/watch?v=9jF3xMqlit4

**Comment by AzureAzel** [comment]
That's one of the weirdest bugs I've seen in awhile. I'm sure there's some wonky reason behind it.

**Comment by shiro-2k** [comment]
Checked it out and I noticed that the gun appears to drop from a different position (noticeable in first-person view) when using the SAS model.

**Comment by 1ci** [comment]
I have attached the fixed model binaries and source code in a ZIP archive.
[Download](https://drive.google.com/file/d/1jkXjlFRES16f1YWkJ4QHd-PQTTha9U-y/view?usp=sharing)

Here is how I fixed it:
I extracted the model files from the .vpk using gcfscape186 and decompiled them using Crowbar v0.71.

I decompiled the other CT models too and spotted the differences between them. Then I made adequate corrections to the SAS model. My assumptions are that there was an improper bone configuration which caused the issue. If I had to guess, it would be this one:

$definebone "ValveBiped" "" 0 0 0 0 0 89.999982 0 0 0 0 0 0

**Comment by wow32134** [comment]
Please fix valve!!!!!

**Comment by megakarlach** [comment]
> Please fix valve!!!!!

Valve is working on newer version of CSS on "frog" branch rn, which presumably will run on TF2 branch (updated Source 2013 MP). Not sure if this bug will be fixed through.

**Comment by cssenjoyer49** [comment]
Still not fixed

**Comment by Ballganda** [comment]
Tested in 2025 updated CSS. Not fixed. Fastest fix here would be to call it a feature not a bug and retcon the lore that the SAS has an injury and can't throw weapons like the others.

**Comment by cssenjoyer49** [comment]
Nah a fix can be made, no story will make sense. they add bhop but can't fix a game breaking bug

**Comment by SirYodaJedi** [comment]
This is allegedly fixed in yesterday's update.

**Comment by Ballganda** [comment]
Appears fixed on my personal test.
