### ISSUE TITLE
[TF2] dragon's fury fireball particle is not fully representative of the projectile

### ISSUE THREAD

**Issue by SirBlockles** [ValveSoftware/Source-1-Games#4028]
there are several instances where the visual fire particle of the dragon's fury fireballs no longer matches up with its projectile. the most common instance of this happening in-game is when it is reflected by an enemy pyro - the projectile is sent back, but the particle continues moving forward through the enemy pyro. the same happens when the projectile is destroyed by a short circuit or simply collides with a wonky map prop.

so far, the only circumstance in the game i have seen change the particle is increasing `tf_fireball_speed`, which makes the particle extend farther or shorter depending on how you change it. note that this, too, is not representative of the actual projectile (as can be seen by enabling `tf_fireball_draw_debug_radius`) unless the `tf_fireball_distance` is increased/decreased by the same factor (eg. 2x)

with this on top of #3897, the entire particle/projectile is probably in need of an internal overhaul.

**Comment by AzureAzel** [comment]
iirc it also collides with syringe gun syringes for some reason, but I'm unsure if that was already addressed or not.

**Comment by SirBlockles** [comment]
> iirc the projectile also collides with syringe gun syringes for some reason, (while the particle itself still exists, it'll do no damage after colliding with a syringe) but I'm unsure if that was already addressed in a previous patch or not.

it was reported and marked as fixed in #3542, but that's not something i've tested directly

**Comment by VirtualSoda** [comment]
The bug where the DF collides with other projectiles has been fixed in the November 15th, 2021 update. 

It is true though that the particle doesn't really represent the actual projectile. Which is a bit of an issue. 
The size of the particle represents the entire hitbox of the fireball (which itself is too big) But now that you need to hit the center of that fireball hitbox to actually get the bonus damage, it is difficult to get a sense of where you exactly need to hit enemies in order to get the bonus damage. 

I suggest making the fireball particle size smaller to represent the center of the entire hitbox. Which this mod has already done: https://github.com/agrastiOs/Ultimate-TF2-Visual-Fix-Pack

**Comment by SirBlockles** [comment]
> I suggest making the fireball particle size smaller to represent the center of the entire hitbox.

that treads matter-of-opinion territory, because i personally prefer the particle representing the entire hitbox of the projectile. it would be quite annoying to have the fireball visually miss you but still get ignited because you weren't hit with the sweetspot but still the outer part of it.

and yeah, the particle was originally designed when the radius was 30 on release, which has now been reduced to 22.5. while i personally think the radius should increase just a tiny bit (like, to 24 or something) it is pretty annoying to have the fireball visually look like it SHOULD have connected but it doesn't simply because the particle was designed for a larger projectile.

**Comment by VirtualSoda** [comment]
> that treads matter-of-opinion territory, because i personally prefer the particle representing the entire hitbox of the projectile, rather than just the center. it would be quite annoying to have the fireball visually miss you but still get ignited because you weren't hit with the sweetspot but still the outer part of it.
> 
> and yeah, the particle was originally designed when the radius was 30 on release, which has now been reduced to 22.5. while i personally think the radius should increase just a tiny bit (like, to 24 or something) it is pretty annoying to have the fireball visually look like it SHOULD have connected but it doesn't simply because the particle was designed for a larger projectile.

I suppose you're right. I definitely agree that the least that should happen is to update the particle size to be apropos for the actual hitbox size
