### ISSUE TITLE
TF2 crashes on official VScript-based VSH maps

### ISSUE THREAD

**Issue by d-k-bo-2** [ValveSoftware/Source-1-Games#5044]
When playing on a (community) server running one of the new VScript-based [VSH](https://wiki.teamfortress.com/wiki/VS_Saxton_Hale_Mode) maps, the game crashes in the first ~5 min. It seems to crash faster the more players there are on the server. If there are no other players on the server (and the game doesn't start), the game doesn't crash.

Playing on a server that runs an older version of Nucleus (vsh_nucleus_b1) doesn't crash the game.

The log reveals that the crash is caused by a segmentation fault.

Both the native Fedora version of Steam and the Flatpak version are affected.

<details>
<summary>Logs</summary>

```
steam.sh[181203]: Running Steam on fedora 38 64-bit
steam.sh[181203]: STEAM_RUNTIME is enabled automatically
setup.sh[181276]: Steam runtime environment up-to-date!
steam.sh[181203]: Steam client's requirements are satisfied
[2023-07-15 16:15:47] Startup - updater built Jul 10 2023 23:58:24
[2023-07-15 16:15:47] Startup - Steam Client launched with: '/home/kbo/.local/share/Steam/ubuntu12_32/steam'
07/15 16:15:47 Init: Installing breakpad exception handler for appid(steam)/version(1689034492)/tid(181351)
[2023-07-15 16:15:47] Loading cached metrics from disk (/home/kbo/.local/share/Steam/package/steam_client_metrics.bin)
[2023-07-15 16:15:47] Using the following download hosts for Public, Realm steamglobal
[2023-07-15 16:15:47] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-07-15 16:15:47] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-07-15 16:15:47] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-07-15 16:15:47] Verifying installation...
[2023-07-15 16:15:47] Verification complete
Loaded SDL version 3.0.0-1782-g214d5daa3
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xecb08170
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xecb06880
GetWin32Stats: display was not open yet, good
ComputeStartupMode: found registry default startup mode: 0
Switching to desktopui, since -vgui was not specified
GetWin32Stats: display was not open yet, good
steamwebhelper.sh[181383]: Runtime for steamwebhelper: defaulting to /home/kbo/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[181383]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
CAppInfoCacheReadFromDiskThread took 27 milliseconds to initialize
Failed to init SteamVR because it isn't installed
local (potentially out of sync) copy of roaming config loaded - 303 bytes.
roaming config store loaded successfully - 303 bytes.
migrating temporary roaming config store
BRefreshApplicationsInLibrary 1: 1ms
System startup time: 3.42 seconds
BuildCompleteAppOverviewChange: 177 apps
RegisterForAppOverview 1: 5ms
RegisterForAppOverview 2: 6ms
ExecCommandLine: "'/home/kbo/.local/share/Steam/ubuntu12_32/steam'"
ExecuteSteamURL: "steam://open/steam://rungameid/440"
ExecuteSteamURL: "steam://rungameid/440"
GameAction [AppID 440, ActionID 1] : LaunchApp changed task to UpdatingAppInfo with ""
GameAction [AppID 440, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 440, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 440, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 440, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 440, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 440, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 gamemoderun /home/kbo/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=440 -- /home/kbo/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/kbo/.local/share/Steam/steamapps/common/Team Fortress 2/hl2.sh' -game tf -steam\0
Game process added : AppID 440 "SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 gamemoderun /home/kbo/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=440 -- /home/kbo/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/kbo/.local/share/Steam/steamapps/common/Team Fortress 2/hl2.sh' -game tf -steam", ProcID 182023, IP 0.0.0.0:0
chdir "/home/kbo/.local/share/Steam/steamapps/common/Team Fortress 2"
ERROR: ld.so: object '/home/kbo/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kbo/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kbo/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 440, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
GameAction [AppID 440, ActionID 1] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/kbo/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
gamemodeauto: 
ERROR: ld.so: object '/home/kbo/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kbo/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
gamemodeauto: 
gamemodeauto: 
pid 182039 != 182038, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/kbo/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kbo/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
SDL video target is 'x11'
SDL video target is 'x11'
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system DOES NOT support the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system supports the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system supports the OpenGL extension GL_NVX_gpu_memory_info.
This system supports the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system supports the OpenGL extension GL_ARB_buffer_storage.
This system supports the OpenGL extension GLX_EXT_swap_control_tear.
OpenGL: AMD Radeon Vega 8 Graphics (raven, LLVM 16.0.5, DRM 3.52, 6.3.8-200.fc38.x86_64) 4.6 (Compatibility Profile) Mesa 23.1.3 (4.6.0)
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_ARB_buffer_storage: NOT AVAILABLE
GL_EXT_texture_sRGB_decode: AVAILABLE
07/15 16:16:10 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(20230710235852)/tid(182055)
07/15 16:16:10 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)/tid(182055)
Using Breakpad minidump system. Version: 8192807 AppID: 440
Setting breakpad minidump AppID = 440
Using breakpad crash handler
[S_API] SteamAPI_Init(): Loaded '/home/kbo/.local/share/Steam/linux32/steamclient.so' OK.
Game process updated : AppID 440 "SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 gamemoderun /home/kbo/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=440 -- /home/kbo/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/kbo/.local/share/Steam/steamapps/common/Team Fortress 2/hl2.sh' -game tf -steam", ProcID 182041, IP 0.0.0.0:0
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
07/15 16:16:10 Init: Installing breakpad exception handler for appid(440)/version(8192807)/tid(182041)
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198213750396 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561198213750396
Did not detect any valid joysticks.
GL_NVX_gpu_memory_info: AVAILABLE
GL_ATI_meminfo: AVAILABLE
GL_NVX_gpu_memory_info: Total Dedicated: 2097152, Total Avail: 11265156, Current Avail: 741256
GL_MAX_SAMPLES_EXT: 8
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 2100 MHz, Processor: AuthenticAMD
GlobalMemoryStatus: 4294967295
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 2100 MHz, Processor: AuthenticAMD
GlobalMemoryStatus: 4294967295
IDirect3DDevice9::Create: BackBufWidth: 1920, BackBufHeight: 1080, D3DFMT: 3, BackBufCount: 1, MultisampleType: 0, MultisampleQuality: 0
GL sampler object usage: DISABLED

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/player/items/taunts/loot_crate/mannco_crate.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/weapons/c_items/c_balloon.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/weapons/c_items/c_balloon_gold.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/weapons/c_items/c_balloon_grenade.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/weapons/c_items/c_balloon_grenade_gold.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/weapons/c_items/c_balloon_grenade_normal.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/weapons/c_items/c_bread_bagged.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/weapons/c_items/c_bread_bagged_normal.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/weapons/c_items/c_bread_robo.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/weapons/c_items/c_bread_shortbread.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/weapons/c_items/c_bread_shortbread_normal.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/weapons/c_items/c_sticky_jumper.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/buildables/mini_dispenser/mini_dispenser.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/buildables/mini_dispenser/mini_dispenser_blue.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/buildables/mini_dispenser/mini_dispenser_phongmask.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/player/items/demo/true_scotsmans_call/true_scotsmans_call_1_blue_color.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/player/items/demo/true_scotsmans_call/true_scotsmans_call_1_color.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/player/items/demo/true_scotsmans_call/true_scotsmans_call_1_normal.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/player/items/demo/true_scotsmans_call/true_scotsmans_call_blue_color.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/player/items/demo/true_scotsmans_call/true_scotsmans_call_color.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/player/items/demo/true_scotsmans_call/true_scotsmans_call_normal.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/player/items/pyro/taunt_spring_rider/taunt_spring_rider_blue_color.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/player/items/pyro/taunt_spring_rider/taunt_spring_rider_color.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/player/items/pyro/taunt_spring_rider/taunt_spring_rider_normal.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/player/items/spy/taunt__au_revoir/taunt__au_revoir_color.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/player/items/spy/taunt_hoodoo_hex/taunt_hoodoo_hex_blue_color.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/player/items/spy/taunt_hoodoo_hex/taunt_hoodoo_hex_color.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/player/items/spy/taunt_sant/taunt_sant_color.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/player/items/spy/taunt_sant/taunt_sant_normal.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/weapons/c_models/c_assault_minigun/c_assault_minigun.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/weapons/c_models/c_dart_gun/c_dart_gun.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/weapons/c_models/c_dart_gun/c_dart_gun_dart.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/weapons/c_models/c_defib/c_defib_red.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/weapons/c_models/c_detonator/c_detonator_phongmask.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/weapons/c_models/c_mortar_launcher/c_mortar_launcher.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/weapons/c_models/c_pilot_flamer/c_pilot_flamer.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/weapons/c_models/c_pilot_flaregun/c_pilot_flare.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/weapons/c_models/c_pilot_flaregun/c_pilot_flaregun.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/weapons/c_models/c_pistol_knife/c_pistol_knife.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/weapons/c_models/c_revolver_sniperrifle/c_revolver_sniperrifle.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/weapons/c_models/c_silenced_pistol_instructor/c_silenced_pistol_instructor.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/weapons/c_models/c_sniperrifle_tv/c_sniperrifle_tv_blue.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/weapons/c_models/c_sniperrifle_tv/c_sniperrifle_tv_red.vtf

 ##### CTexture::LoadTextureBitsFromFile couldn't find materials/models/workshop/weapons/c_models/c_trench_shotgun/c_trench_shotgun.vtf

 ##### swap interval = 0     swap limit = 1 #####
Shader 'shaders\fxc\skin_ps20b.vcs' - Couldn't load combo 860160 of shader (dyn=160)
m_pHardwareShaders was null
Shader 'shaders\fxc\vertexlit_and_unlit_generic_ps20b.vcs' - Couldn't load combo 3833862 of shader (dyn=24)
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
Shader 'shaders\fxc\skin_ps20b.vcs' - Couldn't load combo 860240 of shader (dyn=160)
m_pHardwareShaders was null
Shader 'shaders\fxc\skin_ps20b.vcs' - Couldn't load combo 1998080 of shader (dyn=160)
m_pHardwareShaders was null
Shader 'shaders\fxc\skin_ps20b.vcs' - Couldn't load combo 145200 of shader (dyn=160)
m_pHardwareShaders was null
Shader 'shaders\fxc\vertexlit_and_unlit_generic_ps20b.vcs' - Couldn't load combo 11796864 of shader (dyn=24)
m_pHardwareShaders was null
Shader 'shaders\fxc\skin_ps20b.vcs' - Couldn't load combo 71680 of shader (dyn=160)
m_pHardwareShaders was null
Shader 'shaders\fxc\vertexlit_and_unlit_generic_ps20b.vcs' - Couldn't load combo 884742 of shader (dyn=24)
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
Shader 'shaders\fxc\vertexlit_and_unlit_generic_ps20b.vcs' - Couldn't load combo 1867782 of shader (dyn=24)
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
Shader 'shaders\fxc\vertexlit_and_unlit_generic_ps20b.vcs' - Couldn't load combo 1597440 of shader (dyn=24)
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
m_pHardwareShaders was null
Loaded program cache file "glbaseshaders.cfg", total keyvalues: 266, total successfully linked: 227
Loaded program cache file "glshaders.cfg", total keyvalues: 448, total successfully linked: 448
Precache: Took 531 ms, Vertex 97, Pixel 335
server.so loaded for "Team Fortress"
Unable to remove /home/kbo/.local/share/Steam/steamapps/common/Team Fortress 2/tf/textwindow_temp.html!
IDirect3DDevice9::Reset: BackBufWidth: 1920, BackBufHeight: 1080, D3DFMT: 3, BackBufCount: 1, MultisampleType: 0, MultisampleQuality: 0
[2023-07-15 16:17:48] Background update loop checking for update. . .
[2023-07-15 16:17:48] Checking for available updates...
[2023-07-15 16:17:48] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12?t=1809700665
[2023-07-15 16:17:48] Manifest download: send request
[2023-07-15 16:17:48] Manifest download: waiting for download to finish
[2023-07-15 16:17:49] Manifest download: finished
[2023-07-15 16:17:49] Download skipped: /steam_client_ubuntu12?t=1809700665 version 1689034492, installed version 1689034492, existing pending version 0
[2023-07-15 16:17:49] Nothing to do
Game process updated : AppID 440 "SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 gamemoderun /home/kbo/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=440 -- /home/kbo/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/kbo/.local/share/Steam/steamapps/common/Team Fortress 2/hl2.sh' -game tf -steam", ProcID 182041, IP 75.119.136.2:27016
ERROR: ld.so: object '/home/kbo/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20230715162219_3.dmp[186121]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230715162219_3.dmp
crash_20230715162219_3.dmp[186121]: Finished uploading minidump (out-of-process): success = yes
crash_20230715162219_3.dmp[186121]: response: CrashID=bp-a7b782f4-0272-48b9-aa67-6ff322230715
crash_20230715162219_3.dmp[186121]: file ''/tmp/dumps/crash_20230715162219_3.dmp'', upload yes: ''CrashID=bp-a7b782f4-0272-48b9-aa67-6ff322230715''
gamemodeauto: 
pid 186121 != 186119, skipping destruction (fork without exec?)
/home/kbo/.local/share/Steam/steamapps/common/Team Fortress 2/hl2.sh: line 72: 182041 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game process removed: AppID 440 "SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 gamemoderun /home/kbo/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=440 -- /home/kbo/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/kbo/.local/share/Steam/steamapps/common/Team Fortress 2/hl2.sh' -game tf -steam", ProcID 182041 
ThreadGetProcessExitCode: no such process 186119
ThreadGetProcessExitCode: no such process 182041
ThreadGetProcessExitCode: no such process 182040
ThreadGetProcessExitCode: no such process 182038
Game 440 created interface STEAMAPPLIST_INTERFACE_VERSION001 / 
Game 440 created interface STEAMAPPS_INTERFACE_VERSION008 / 
Game 440 created interface STEAMHTMLSURFACE_INTERFACE_VERSION_005 / 
Game 440 created interface STEAMHTTP_INTERFACE_VERSION003 / 
Game 440 created interface STEAMHTTP_INTERFACE_VERSION003 / HTTP
Game 440 created interface STEAMINVENTORY_INTERFACE_V003 / 
Game 440 created interface STEAMMUSICREMOTE_INTERFACE_VERSION001 / 
Game 440 created interface STEAMMUSIC_INTERFACE_VERSION001 / 
Game 440 created interface STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / 
Game 440 created interface STEAMREMOTESTORAGE_INTERFACE_VERSION014 / 
Game 440 created interface STEAMSCREENSHOTS_INTERFACE_VERSION003 / 
Game 440 created interface STEAMUGC_INTERFACE_VERSION015 / 
Game 440 created interface STEAMUSERSTATS_INTERFACE_VERSION012 / 
Game 440 created interface STEAMVIDEO_INTERFACE_V002 / 
Game 440 created interface SteamController008 / 
Game 440 created interface SteamFriends017 / 
Game 440 created interface SteamGameCoordinator001 / 
Game 440 created interface SteamGameStats001 / 
Game 440 created interface SteamInput003 / 
Game 440 created interface SteamMatchGameSearch001 / 
Game 440 created interface SteamMatchMaking009 / 
Game 440 created interface SteamMatchMakingServers002 / 
Game 440 created interface SteamNetworking006 / 
Game 440 created interface SteamNetworkingSocketsSerialized005 / 
Game 440 created interface SteamUser021 / 
Game 440 created interface SteamUser021 / User
Game 440 created interface SteamUtils002 / Utils
Game 440 created interface SteamUtils010 / 
Game 440 created interface SteamUtils010 / Utils
Game 440 method call count for IClientNetworkingUtilsSerialized::GotLocationString : 2
Game 440 method call count for IClientNetworkingSocketsSerialized::GetSTUNServer : 2
Game 440 method call count for IClientNetworkingSocketsSerialized::GetCachedRelayTicketCount : 1
Game 440 method call count for IClientControllerSerialized::GetAnalogActionHandle : 2
Game 440 method call count for IClientControllerSerialized::GetDigitalActionHandle : 49
Game 440 method call count for IClientControllerSerialized::GetActionSetHandle : 4
Game 440 method call count for IClientUGC::GetSubscribedItems : 1
Game 440 method call count for IClientUGC::GetNumSubscribedItems : 1
Game 440 method call count for IClientAudio::GetVoiceOptimalSampleRate : 1
Game 440 method call count for IClientHTTP::ReleaseHTTPRequest : 5
Game 440 method call count for IClientHTTP::GetHTTPResponseBodyData : 5
Game 440 method call count for IClientHTTP::GetHTTPResponseBodySize : 2
Game 440 method call count for IClientHTTP::SendHTTPRequest : 5
Game 440 method call count for IClientHTTP::SetHTTPRequestHeaderValue : 3
Game 440 method call count for IClientHTTP::SetHTTPRequestNetworkActivityTimeout : 1
Game 440 method call count for IClientHTTP::CreateHTTPRequest : 5
Game 440 method call count for IClientGameStats::GetNewSession : 1
Game 440 method call count for IClientGameCoordinator::RetrieveMessage : 70
Game 440 method call count for IClientGameCoordinator::IsMessageAvailable : 141
Game 440 method call count for IClientGameCoordinator::SendMessage : 30
Game 440 method call count for IClientConfigStore::GetString : 4
Game 440 method call count for IClientConfigStore::GetInt : 4
Game 440 method call count for IClientRemoteStorage::IsCloudEnabledForApp : 1
Game 440 method call count for IClientRemoteStorage::FileExists : 3
Game 440 method call count for IClientRemoteStorage::GetFileSize : 4
Game 440 method call count for IClientRemoteStorage::FileRead : 2
Game 440 method call count for IClientRemoteStorage::FileWrite : 1
Game 440 method call count for IClientUserStats::GetDownloadedLeaderboardEntry : 41
Game 440 method call count for IClientUserStats::DownloadLeaderboardEntries : 18
Game 440 method call count for IClientUserStats::GetLeaderboardEntryCount : 13
Game 440 method call count for IClientUserStats::FindLeaderboard : 220
Game 440 method call count for IClientUserStats::GetAchievement : 520
Game 440 method call count for IClientUserStats::StoreStats : 1
Game 440 method call count for IClientUserStats::GetStat : 753
Game 440 method call count for IClientUserStats::RequestCurrentStats : 1
Game 440 method call count for IClientAppManager::GetCurrentLanguage : 3
Game 440 method call count for IClientAppManager::GetLaunchCommandLine : 2
Game 440 method call count for IClientAppManager::GetAppStateInfo : 1
Game 440 method call count for IClientAppManager::BIsDlcEnabled : 1
Game 440 method call count for IClientMatchmaking::EnsureFavoriteGameAccountsUpdated : 2
Game 440 method call count for IClientMatchmaking::ReleaseGMSQuery : 2
Game 440 method call count for IClientMatchmaking::GetGMSQueryResults : 2
Game 440 method call count for IClientMatchmaking::PollGMSQuery : 50
Game 440 method call count for IClientMatchmaking::BeginGMSQuery : 2
Game 440 method call count for IClientMatchmaking::GetLobbyOwner : 2
Game 440 method call count for IClientMatchmaking::AddFavoriteGame : 1
Game 440 method call count for IClientMatchmaking::GetFavoriteGame : 388
Game 440 method call count for IClientMatchmaking::GetFavoriteGameCount : 6
Game 440 method call count for IClientUtils::RecordSteamInterfaceCreation : 146
Game 440 method call count for IClientUtils::FilterText : 3152
Game 440 method call count for IClientUtils::InitFilterText : 1
Game 440 method call count for IClientUtils::IsSteamChina : 1
Game 440 method call count for IClientUtils::GetLauncherType : 1
Game 440 method call count for IClientUtils::SetAPICallResultWithoutPostingCallback : 2
Game 440 method call count for IClientUtils::AllocPendingAPICallHandle : 2
Game 440 method call count for IClientUtils::GetAPICallResult : 244
Game 440 method call count for IClientUtils::GetAppID : 153
Game 440 method call count for IClientUtils::GetImageRGBA : 49
Game 440 method call count for IClientUtils::GetImageSize : 49
Game 440 method call count for IClientUtils::GetIPCountry : 1
Game 440 method call count for IClientUtils::GetServerRealTime : 13
Game 440 method call count for IClientFriends::GetFriendPersonaName_Public : 115
Game 440 method call count for IClientFriends::SetRichPresence : 24
Game 440 method call count for IClientFriends::RequestUserInformation : 86
Game 440 method call count for IClientFriends::GetFriendGamePlayed : 14
Game 440 method call count for IClientFriends::GetFriendByIndex : 135
Game 440 method call count for IClientFriends::GetFriendCount : 15
Game 440 method call count for IClientFriends::GetMediumFriendAvatar : 3
Game 440 method call count for IClientFriends::GetSmallFriendAvatar : 46
Game 440 method call count for IClientFriends::GetFriendPersonaState : 126
Game 440 method call count for IClientFriends::GetFriendRelationship : 12
Game 440 method call count for IClientFriends::HasFriend : 95
Game 440 method call count for IClientFriends::GetPersonaName : 60
Game 440 method call count for IClientUser::BIsSubscribedApp : 1
Game 440 method call count for IClientUser::AdvertiseGame : 1
Game 440 method call count for IClientUser::GetAuthSessionTicket : 1
Game 440 method call count for IClientUser::GetSteamID : 548
Game 440 method call count for IClientUser::BLoggedOn : 5
Uploaded AppInterfaceStats to Steam

(process:182055): GLib-GObject-CRITICAL **: 16:22:30.516: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
reaping pid: 182055 -- gameoverlayui
[2023-07-15 16:22:46] Shutdown
```

</details>

[crash_20230715162219_3.dmp.gz](https://github.com/ValveSoftware/Source-1-Games/files/12061924/crash_20230715162219_3.dmp.gz)

<details>
<summary>Short System Information</summary>

```
OS: Fedora Linux 38 (Workstation Edition) x86_64 
Host: 81N6 Lenovo ideapad C340-14API 
Kernel: 6.3.8-200.fc38.x86_64 
Uptime: 4 hours, 37 mins 
Packages: 3667 (rpm), 140 (flatpak) 
Shell: fish 3.6.1 
Resolution: 1920x1080 
DE: GNOME 44.2 
WM: Mutter 
WM Theme: Adwaita 
Theme: adw-gtk3-dark [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: kgx 
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz 
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
Memory: 7088MiB / 17906MiB
```

</details>

<details>
<summary>Full System Information</summary>

```
Computer Information:
Manufacturer: LENOVO
Model: LNVNB161216
Form Factor: Laptop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
CPU Family: 0x17
CPU Model: 0x18
CPU Stepping: 0x1
CPU Type: 0x0
Speed: 2100 MHz
8 logical processors
4 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
Fedora Linux 38 (Workstation Edition) (64 bit)
Kernel Name: Linux
Kernel Version: 6.3.8-200.fc38.x86_64
X Server Vendor: The X.Org Foundation
X Server Release: 12201009
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20230509.49499
Video Card:
Driver: AMD AMD Radeon Vega 8 Graphics (raven, LLVM 16.0.5, DRM 3.52, 6.3.8-200.fc38.x86_64)
Driver Version: 4.6 (Compatibility Profile) Mesa 23.1.3
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID: 0x1002
DeviceID: 0x15d8
Revision Not Detected
Number of Monitors: 2
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 3456 x 1080
Primary Display Size: 20.87" x 11.81" (23.98" diag), 53.0cm x 30.0cm (60.9cm diag)
Primary VRAM: 2048 MB
Sound card:
Audio device: ATI R6xx HDMI
Memory:
RAM: 17906 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: de_DE.UTF-8
Total Hard Disk Space Available: 952244 MB
Largest Free Hard Disk Block: 492475 MB
Storage:
Number of SSDs: 1
SSD sizes: 1000G
Number of HDDs: 0
Number of removable drives: 0
```

</details>

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a SIGSEGV in studiorender.so.

**Comment by AzureWoof** [comment]
> When playing on a (community) server running one of the new VScript-based [VSH](https://wiki.teamfortress.com/wiki/VS_Saxton_Hale_Mode) maps, the game crashes in the first ~5 min. It seems to crash faster the more players there are on the server. If there are no other players on the server (and the game doesn't start), the game doesn't crash.
> 
> Playing on a server that runs an older version of Nucleus (vsh_nucleus_b1) doesn't crash the game.

Hello, @d-k-bo-2 .

I've recently ran into a similar issue, and I ended up fixing it by deleting every sound.cache file I could find in the "tf" folder.
I know it sounds odd, but please give this a try and let me know what happens.

Thanks.

**Comment by Septimustache1** [comment]
> I've recently ran into a similar issue, and I ended up fixing it by deleting every sound.cache file I could find in the "tf" folder. I'm thinking that sound.cache files are corrupting rather easily due to the new gamemode for some reason. I know it sounds odd, but please give this a try and let me know what happens.

This seems to work, but the sound.cache files keep showing up in the sound and soundworkshop folders while I'm playing and crashing me again. Deleting those folders doesn't work either.

**Comment by d-k-bo-2** [comment]
> I ended up fixing it by deleting every sound.cache file I could find in the "tf" folder

Unfortunately, that doesn't help in my case.

**Comment by DeeJayLSP** [comment]
Now that it has been added back to matchmaking, I can confirm it also happens there.

Using Ubuntu 22.04 btw.

**Comment by Stargost** [comment]
This is happening to me too. However, I'm on a Windows laptop instead of Linux. After around 5~ minutes the game crashes.

**Comment by DocRaphael** [comment]
I am too using a Windows laptop and I too crash in seemingly random intervals. 
Even after I deleted every sound.cache file and booted up the game with -nosound the error still persisted.
Looking into the windows event log there seems to be some error in the studiorender.dll.
I am not familiar with C/C++ and just wanted to point this out.

**Comment by Jgr9** [comment]
Same here.  Somebody on the mailing list says it's a similar issue to Bread Space I think.

**Comment by Ashetf2** [comment]
Hopefully fixed in today's update: "Fixed a crash that can occur when changing from VSH to another map". Please retest

**Comment by DeeJayLSP** [comment]
Just tested and it crashed seconds after I spawned.

**Comment by Ashetf2** [comment]
Maybe it is related to another bug

**Comment by DocRaphael** [comment]
Its fixed for me.

**Comment by Jgr9** [comment]
I'm not sure which of the several VSH crashes is still happening, but I crashed at like the 3rd VSH match/map of the night, probably different servers.  Also, the first one I joined was Matchmaking 2 full teams, no Saxton, and the match wouldn't start.  This, and the crash on the 3rd VSH map of the night, was the day after the July 25th update.

**Comment by alkaris2** [comment]
VSH maps seems to crash more often as they're bugged, sometimes can't go more than a minute without crashing. Plus the blood textures on Saxton stretches across the map which is causing all sorts of issues in most cases, which is probably the main cause of the crashes happening. Did some testing just on a private server with 17 bots spawned with `tf_bot_add` and it's consistent whenever that texture is stretched and anchored to a specific area of the map itself. Snapping to origin 0, 0, 0 on the XYZ axis of the map itself. Crashes can also happen if there's a lot of gibs and particle effects from Saxton's punch as well as other particle effects that happen to be displayed also. Some suggest setting `mat_phong 0` but this doesn't have any effect from the crashes that still happens.

**Comment by L1nkus** [comment]
Same issue. Often crashing instantly when joining an official VSH server

**Comment by DeeJayLSP** [comment]
One detail I should mention: I my game never crashed while playing as Hale (it actually did some times after winning) or spectating him. Maybe the crash is somewhat related to his 3rd person model.

**Comment by Jgr9** [comment]
Joined as spectator.  Crashed a few minutes into the first round I was playing.

**Comment by DeeJayLSP** [comment]
Also, VSH maps other than vsh_nucleus tend to crash faster.

**Comment by Jgr9** [comment]
First map of the night, crashed as soon as I started firing as Heavy, but crashes as any class it seems.

**Comment by Jgr9** [comment]
Setting r_drawmodeldecals 0 seemed to work.

Intel CPU graphics if that makes any difference.

**Comment by NULLYUKI** [comment]
To be able to provide a crash log that will help identify the issue, please follow these steps:

1. Create a `autoexec.cfg` inside the `tf/cfg` folder with the following commands:
```
con_enable "1" //Make sure console is enabled on start up
con_timestamp "1" //Adds timestamp so you can easily find output for when your crash is
con_logfile "cfg/tf/console_log" //Location of console log file
developer "4" //4: Highest(?) level of debugging information; I/O events print to console, bounding boxes can show up on objects with VPhysics errors, etc.
```
2. Start the game
3. Play VSH until a crash occurs
4. Post the crash log here

This should help out Valve and other players to identify the cause of the crashes.
The guide how to get crash logs was found by this discussion post "[Crash log location?](https://steamcommunity.com/app/440/discussions/0/1744480966984639577/#c1744480966985167704)"

**Comment by DeeJayLSP** [comment]
I didn't get to use the crash log.

However, I can confirm disabling model decals with `r_drawmodeldecals 0` prevent crash.

**Comment by DocRaphael** [comment]
> Setting r_drawmodeldecals 0 seemed to work.
> 
> Intel CPU graphics if that makes any difference. (before Xe or whatever)
After playing around 8 games it crashed for me despite having r_drawmodeldecals set to 0.
So it doesnt seem to be a solution for everyone.

**Comment by NULLYUKI** [comment]
Would be good to have the error message or a crash log, to identify the cause of the issue somehow.
