### ISSUE TITLE
[TF2] [x64_test] Servers with SDR enabled causes the server browser to show that it has 255 players.

### ISSUE THREAD

**Issue by gaelcoral** [ValveSoftware/Source-1-Games#5507]
Title
![image](https://github.com/ValveSoftware/Source-1-Games/assets/63524243/001cb959-f8d0-4352-912a-90644bde6bb8)

https://github.com/ValveSoftware/Source-1-Games/assets/63524243/0627db25-484b-4aa7-9c99-b46da607a25f

**Comment by gaelcoral** [comment]
Fixed!
![image](https://github.com/ValveSoftware/Source-1-Games/assets/63524243/aeba4778-89a0-49a4-a362-d8df9fe47e00)

**Comment by gaelcoral** [comment]
Still happening
![image](https://github.com/ValveSoftware/Source-1-Games/assets/63524243/fb3a35cb-5f97-4716-88a8-3be7611e9b5e)

**Comment by Goosegit11** [comment]
same

**Comment by WickeDxJay** [comment]
Still not fixed? 

![Image](https://github.com/user-attachments/assets/37b4276c-bc62-40e5-8d88-f40a2aabf800)
