### ISSUE TITLE
Mercenary's eyes are the missing texture (black, purple).

### ISSUE THREAD

**Issue by Njit2098** [ValveSoftware/Source-1-Games#5717]
I found this out in the loadout menu, haven't seen if its in matches aswell.

**Comment by MickMundy** [comment]
I have been having this issue as well. It has been occurring since the 64 bit update. To my knowledge it is only occurring on AMD cards. Happens after server change or first server load in, rather inconsistent to reproduce. This bug can **_sometimes_** be fixed by toggling mat_phong off/on but this is also inconsistent.

Getting these errors in the console when the bug manifests itself. 
```
Requesting texture value from var "$envmap" which is not a texture value (material: models/player/scout/eyeball_l)
Requesting texture value from var "$envmap" which is not a texture value (material: models/player/scout/eyeball_r)
Requesting texture value from var "$envmap" which is not a texture value (material: models/player/sniper/eyeball_l)
Requesting texture value from var "$envmap" which is not a texture value (material: models/player/sniper/eyeball_r)
``` 
etc. for the other classes

When I looked at the materials and textures in tf2's vpks, there doesn't seem to be any issue that the error messages are reporting, the envmap variable is directing to the correct shared eye cubemap.

**Comment by Churkinator** [comment]
I never experienced this issue in-game, but I have 2 guesses why it can occur.

1) TF2 tries to find HDR texture of the eye cubemap when you play with enabled HDR, but can't find it because it doesn't exist, and as a result it just shows the missing texture.

2) Basically [#4848](https://github.com/ValveSoftware/Source-1-Games/issues/4848). Eye textures just randomly uncache and as a result show the missing texture or become fully white.

Update: 3) Probably it also slightly related to #4937. I'm not sure about it, but if the EyeRefract shader is somehow affects Water shader, then it can also mean that Water shader somehow affects EyeRefract shader.

For the first one, I created the HDR texture of the eye cubemap by using files from the 2023 repo leak. Since, again, I did not see this issue in-game, I can't test if it fixes the issue or not, so feedback would be appreciated.

[HDR eyes texture.zip](https://github.com/user-attachments/files/19821503/HDR.eyes.texture.zip)

**Comment by RiverHornet3209** [comment]
I have the same issue where the eyes have missing textures

<img width="229" height="213" alt="Image" src="https://github.com/user-attachments/assets/be69751f-73eb-48d4-a5a3-89384c47f322" />

<img width="456" height="576" alt="Image" src="https://github.com/user-attachments/assets/1e762a37-849c-42e2-90ce-204bc46bdc94" />

<img width="439" height="727" alt="Image" src="https://github.com/user-attachments/assets/9ed87e9b-cde2-4b2f-9e99-1d48eb06ef67" />

My TF2 Version:
```
Build Label:          10139465   # Uniquely identifies each build
Network PatchVersion: 10139465   # Determines client and server compatibility
Protocol version:           24   # High level network protocol version
Server version:       10139465
Server AppID:           232250
Client version:       10139465
Client AppID:              440
```

My system specs: https://gist.github.com/RiverHornet3209/5e86b71dfa2f4d6b219efdb05bded7ce

**Comment by RiverHornet3209** [comment]
> For the first one I created HDR texture of the eye cubemap by using files from the 2023 repo leak. Since, again, I did not see this issue in-game, I can't test if it fixes the issue or not, so feedback would be appreciated.
> 
> [HDR eyes texture.zip](https://github.com/user-attachments/files/19821503/HDR.eyes.texture.zip)

This mod doesn't fix the missing texture eye bug
(btw I put the "HDR eyes texture.vpk" file in the `Team Fortress 2/tf/custom` folder)

**Comment by SpaceJesusCosmic** [comment]
![Image](https://github.com/user-attachments/assets/221a41c5-dd25-40e6-a1ae-a4115ac39060)

![Image](https://github.com/user-attachments/assets/5111aa36-1935-4baf-ad24-a05e3f405fd2)




> [HDR eyes texture.zip](https://github.com/user-attachments/files/19821503/HDR.eyes.texture.zip)

Tried the same as @RiverHornet3209 

RTX 2070 / Windows 10 x64  
TF2 64-bit build (Nov 2025)  
All mercenary pupils render pure white, not missing texture.  
Tried r_eyes 1, r_eyegloss 1, mat_envmaps 1, mat_reloadallmaterials, mat_specular 0, mat_phong 0. no change.  
Clean config (mastercomfig + RLE + UVFP), verified files, driver rollback tested
Likely envmap/reflection vector failure in eyeball.vmt under 64-bit shader pipeline

**Comment by rotip309** [comment]
Somehow this bug still exists. I wonder if there is some work around or a fix. Funnily enough, it does not happen on every map. Since I did a round of 2fort and everyone's eyes were normal, but then tried on newer maps and they were completely broken

does only happens on amd cards?
