### ISSUE TITLE
[TF2] [Linux] Frame Rate quickly osolates between a very low, and regular amount.

### ISSUE THREAD

**Issue by sweglord227** [ValveSoftware/Source-1-Games#5785]
### BUG

After about 30 minutes in game, I begin to experience stutters caused by an extreme variance in my frames. `cl_showfps 2` says my min is ~18 immediately after turning it on. This persists even outside of gameplay, in the main menu. I don't notice anything out of the ordinary in console. If you need anything else from me, please let me know.

### SPECS

```
Operating System Version:
"Arch Linux" (64 bit)
Kernel Name: Linux
Kernel Version: 6.8.6-zen1-1-zen
X Server Vendor: The X.Org Foundation
X Server Release: 12302006
X Window Manager: Hyprland
Steam Runtime Version: steam-runtime_0.20240415.84615
```

```
Video Card:
Driver: AMD AMD Radeon RX 6700 XT (radeonsi, navi22, LLVM 17.0.6, DRM 3.57, 6.8.6-zen1-1-zen)
Driver Version: 4.6 (Compatibility Profile) Mesa 24.0.5-arch1.1
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 119 Hz
VendorID: 0x1002
DeviceID: 0x73df
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.47" x 11.42" (23.43" diag), 52.0cm x 29.0cm (59.5cm diag)
Primary VRAM: 12288 MB
```

**Comment by kisak-valve** [comment]
Hello @sweglord227, your symptoms remind me of https://github.com/ValveSoftware/csgo-osx-linux/issues/2901. Do you happen to have the Steam overlay disabled with the game and if you do, does enabling it have an effect?

**Comment by sweglord227** [comment]
i do have steam overlay disabled. i can try running the game again with it on. however looking a little closer a some other issues, this could be a duplicate of #5767. i'll get back to you in 30-45 minutes.

**Comment by sweglord227** [comment]
alright 53 minutes into this session and it hasn't started yet. it's likely safe to assume that was the problem. i'm gonna keep my client running for a bit into the night tho to see if i just got lucky this time.

**Comment by sweglord227** [comment]
overlay was indeed the problem. kinda makes me curious as to why having it disabled would cause issues with rendering/frame rates

**Comment by eeceebee** [comment]
Can confirm that this worked for me as well!

Runs flawlessly with the steam overlay enabled. I had it disabled in the past due to previous performance issues with it on.

**Comment by lkirkwood** [comment]
Thank you this worked for me aswell

**Comment by Espionage724** [comment]
I'm curious about this! I never imagined having Steam's overlay disabled could lead to performance issues.

Edit: I wonder, was the overlay hiding a problem? Maybe it was lowering overall performance thus preventing garbage collection or a memory overuse. Maybe something with framerate limiting and a CPU sleep (like NVIDIA USLEEP and YIELD stuff)?

**Comment by sirlucidae** [comment]
I have experienced the same problems recently with several different games in Steam, where performance was fine in the beginning but at a certain point began to deteriorate. After some trial-and-error I found that disabling the overlay did lead to this behavior.

**Comment by Suphax** [comment]
Same here - noticed lots of stuttering in TF2 after 30-60 minutes (time varies). Re-enabling Steam overlay fixed the issue.

System:
  Kernel: 6.8.0-55-generic arch: x86_64 bits: 64 compiler: gcc v: 13.3.0 clocksource: tsc
  Desktop: Cinnamon v: 6.4.8 tk: GTK v: 3.24.41 wm: Muffin v: 6.4.1 vt: 7 dm: LightDM v: 1.30.0
    Distro: Linux Mint 22.1 Xia base: Ubuntu 24.04 noble
Machine:
  Type: Desktop System: Gigabyte product: Z590 VISION G v: -CF serial: <superuser required>
  Mobo: Gigabyte model: Z590 VISION G serial: <superuser required> uuid: <superuser required>
    UEFI: American Megatrends LLC. v: F9 date: 12/19/2023
Battery:
  ID-1: hidpp_battery_0 charge: 67% condition: N/A volts: 3.9 min: N/A model: Logitech G502
    LIGHTSPEED Wireless Gaming Mouse type: N/A serial: <filter> status: discharging
CPU:
  Info: 6-core model: 11th Gen Intel Core i5-11600K bits: 64 type: MT MCP smt: enabled
    arch: Rocket Lake rev: 1 cache: L1: 480 KiB L2: 3 MiB L3: 12 MiB
  Speed (MHz): avg: 4599 high: 4601 min/max: 800/4900 cores: 1: 4600 2: 4600 3: 4600 4: 4600
    5: 4600 6: 4600 7: 4600 8: 4591 9: 4601 10: 4600 11: 4601 12: 4600 bogomips: 93888
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: NVIDIA GA106 [GeForce RTX 3060 Lite Hash Rate] vendor: ASUSTeK driver: nvidia
    v: 550.120 arch: Ampere pcie: speed: 16 GT/s lanes: 16 ports: active: none
    off: DP-1,DP-2,HDMI-A-1 empty: DP-3 bus-ID: 01:00.0 chip-ID: 10de:2504 class-ID: 0300
  Screen-1: 0 s-res: 6400x1440 s-dpi: 92 s-size: 1766x401mm (69.53x15.79") s-diag: 1811mm (71.3")
  Monitor-1: DP-0 pos: primary,top-center res: 2560x1440 hz: 165 dpi: 108
    size: 600x340mm (23.62x13.39") diag: 690mm (27.15") modes: N/A
  Monitor-2: DP-2 pos: bottom-l res: 1920x1080 dpi: 93 size: 527x296mm (20.75x11.65")
    diag: 604mm (23.8") modes: N/A
  Monitor-3: HDMI-0 pos: middle-r res: 1920x1080 dpi: 93 size: 527x296mm (20.75x11.65")
    diag: 604mm (23.8") modes: N/A
Info:
  Memory: total: 128 GiB note: est. available: 125.67 GiB used: 8.94 GiB (7.1%)
  Processes: 361 Power: uptime: 7h 17m states: freeze,mem,disk suspend: deep wakeups: 0
    hibernate: platform Init: systemd v: 255 target: graphical (5) default: graphical
  Compilers: gcc: 13.3.0 Client: Cinnamon v: 6.4.8 inxi: 3.3.34

**Comment by Suphax** [comment]
Same here - noticed lots of stuttering in TF2 after 30-60 minutes (time varies). Re-enabling Steam overlay fixed the issue.

![Image](https://github.com/user-attachments/assets/8e0f91e8-8974-4e08-bf40-382ba7aa292c)

**Comment by elde-n** [comment]
This happens on all source1 games with 64bit I think, had the same issue on counter strike source and tf2

**Comment by nipnipj** [comment]
I'll test this!

**Comment by nipnipj** [comment]
My experience improved. The sudden huge fps drops are gone. I still have some low fps (~70) some times, but i think it is because I have a 10600k CPU and the game is now 20 vs 20 dustbowl.

**Comment by torzod** [comment]
having this issue here too after i disabled the overlay as it is causing the game to crash immediately on launch. looks like i'm either not playing the game or playing with inevitable stutter, usually after a while of playing but sometimes immediately. i know which i will be choosing for the time being, but i do hope that both of these issues are resolved soon

**Comment by marcos351f** [comment]
I would say that Left 4 Dead 2 is TOTALLY UNPLAYABLE on Linux for me. Different machines, same bad experience. That is sad since I love this game. I have about 2500+ hours of gameplay.

Enabling Steam Overlay seems to help a bit. But the game randomly crashes both on Vulkan and OpenGL. In certain maps important parts of the scene disappear after some time, requiring a restart. This is another issue not related to this stuttering. Based on the date of the release I cannot expect this to be fixed, besides all efforts to improve gaming experience on Linux that Valve is achieving.

**Comment by nipnipj** [comment]
Update. After installing TF2 the game didn't start at all and I had to use "legacy opengl". I just change it back to "play team fortress 2". The performance improved a lot. I still have some small fps drops but not as before. Maybe some one with better hardware can test it.

**Comment by nipnipj** [comment]
Using wayland, the performance is even better. I was using x11.
Experiment with `LD_PRELOAD="" %command%`. It might boost fps.

**Comment by nipnipj** [comment]
This helps a lot with those FPS drops.
https://comfig.app/app/

**Comment by THENATHE** [comment]
This is occurring for me in all games after a variable amount of time (consistent for the game) even with the overlay turned ON. I believe it is the issue because LD PRELOAD="" does fix the issue, but it blocks steam overlay (which I need for gamepad input).
