### ISSUE TITLE
Invisible Enemy or Teammates TF2

### ISSUE THREAD

**Issue by SpyAmogus0417** [ValveSoftware/Source-1-Games#6105]
So when you lag or when your fps decreases or when u r having trouble with your connection, sometimes the character model of an enemy or teammate dissapear... But, they still can attack you just that you cannot see them. I dont have a screenshot of it but, it happens most of the times for me....

**Comment by JoriKos** [comment]
Which game?

**Comment by SpyAmogus0417** [comment]
tf2
probably any valve game but idk

**Comment by SpyAmogus0417** [comment]
> Which game?
tf2

**Comment by kisak-valve** [comment]
Possible duplicate of #6015.

**Comment by Tiagoquix** [comment]
I think this is the bug which is fixed by `record fix;stop` via the developer console. If this is the case, then it's cross-platform. OP hasn't given much details, so I can't be sure.

**Comment by jh34ghu43gu** [comment]
Probably windows duplicate #2659 or linux duplicate 6015 like kisak said. The core issue is a client-server desync which can be triggered by alt-tab for some people, or just having your connection drop for long enough (either due to network reasons or extremely bad frame drops could potentially cause it as well). As mentioned, starting a demo recording resyncs the client and makes everything visible again. 

Another symptom of this desync is #3352.

**Comment by SpyAmogus0417** [comment]
> I think this is the bug which is fixed by `record fix;stop` via the developer console. If this is the case, then it's cross-platform. OP hasn't given much details, so I can't be sure.

ill try :)

edit : it worked :D

**Comment by JoriKos** [comment]
I wouldn't note this as completed, as this is still an issue that happens. This is not a duplicate of any of the issues mentioned before, because it mostly has to do with a desync rather than alt tabbing. But yes, this is a cross-platform issue as I've had this bug numerous times on different Windows versions (7, 8/8.2, and 10)
