### ISSUE TITLE
[Steam Client \ TF2] Steam "Recently Played With" Module No Longer Detects TF2 Matches

### ISSUE THREAD

**Issue by Kacey2k** [ValveSoftware/Source-1-Games#6242]
Hello,

_I believe this is a separate issue from #4692 as that one was reporting the lack of game info details, as opposed to the entire module failing to work as intended._

Currently, the module on Steam does not report *any* details about TeamFortress 2 related matches.

The module used in the In-Game Overlay does report recent players, however.

![image](https://github.com/user-attachments/assets/b80e17bf-281d-4015-bdd9-00701c10b61d)

**Comment by ethanholt1** [comment]
This may be an issue with your individual setup. The module for me consistently reports who I've matched with, even in community servers. 
What platform are you running the game on, and are you playing in Community or Valve servers?

**Comment by gaelcoral** [comment]
I think it is already fixed

![image](https://github.com/user-attachments/assets/0f325e21-41de-4307-96bd-568af3f2243e)

**Comment by ethanholt1** [comment]
I don't think this was ever broken, moreover that this one specific issue was a one off and not a symptom of a larger issue.

Also, observed to have been fixed on my copy of the game.

**Comment by kisak-valve** [comment]
Closing as a fluke.

**Comment by ernestask** [comment]
Not a fluke, this hasn’t worked for me once.

I use Arch, btw.

<img width="920" height="574" alt="Image" src="https://github.com/user-attachments/assets/6c909031-983c-4dc9-a42f-47054bb980df" />

**Comment by Kacey2k** [comment]
Update

I could've given more info on this back when I first reported it.

I play on Windows 10, and across Community & Valve servers.

To this day since posting, it has not worked as it should --- **except** for some occasions showing 1 or 2 players who were partied with me in-game, but still missing the dozens of other unique players encountered during the session:

<img width="958" height="371" alt="Image" src="https://github.com/user-attachments/assets/560cdb76-5865-4498-8261-e77fdba37d1e" />


Note: The In-Game Overlay's _Recently Played With_ feature works as advertised. So, it's strange this persists to be an issue when player tracking seems to be working there.

@kisak-valve maybe this should be re-opened
