### ISSUE TITLE
[TF2] Some contracts in the community_maps_5 node don't work correctly

### ISSUE THREAD

**Issue by StressedCatInABox** [ValveSoftware/Source-1-Games#6443]
A few of the new contracts do not work properly, and one currently does not work at all. Experienced these bugs yesterday, and they seem to not have been fixed yet.

`zi_blazehattan`'s contract does not function **at all** on casual servers, displays as if inactive. 
![image](https://github.com/user-attachments/assets/4efc135b-2a74-4189-8fef-43057bb4f71c)

`vsh_outburst`'s contract has a somewhat broken bonus objective. "Win a round as a Merc" does not give you points for being on the winning team, but seemingly only for killing Saxton yourself or assisting in Saxton's death.
In the following clip I do not kill Saxton or get an assist kill on him and get no points, then another Merc kills Hale with a shotgun and says he got the point on his contract.
https://github.com/user-attachments/assets/8c59ce96-6303-4085-884c-eec7cc2bb6a4

![image](https://github.com/user-attachments/assets/d1527aba-8b5a-42a0-b297-8d11f432f46f)

Dying on `pd_circus`  seems to count as collecting Funny Bones... somehow? [A similar bug is listed for Pit of Death on the wiki page for Halloween Contracts.](https://wiki.teamfortress.com/wiki/Halloween_Contracts#Bugs)

If anyone else experiences these bugs, please share a clip of it! :D

**Comment by StressedCatInABox** [comment]
#6435 seems to support this idea.
I can also confirm that the "Deal 1000 damage as a Merc" objective activates on every hit as well.

EDIT: @KimmyTF2 has recorded the "Win a round as a Merc" objective working, but it still doesn't seem to give you points for being on the winning team, only for killing Saxton or assist-killing him.

**Comment by KimmyTF2** [comment]
Blazehattan contract is indeed not working at all

https://github.com/user-attachments/assets/80cc9669-5567-47f7-9f69-f9d9d29c7ce8

**Comment by StressedCatInABox** [comment]
I have edited the initial post to clarify a few things. Seems that "Win a round as a Merc" **isn't impossible** to do, but is either worded poorly or not working as intended...?

**Comment by ahw4546** [comment]
1. You misspelled `zi_blazehattan`
2. Contracts inactive not because of `mp_tournament` but because Valve set the map in the mission file to `zi_blazehattan_b2`

**Comment by StressedCatInABox** [comment]
I've fixed the spelling mistake, thanks for pointing that out.
Where are the mission files stored? I wanted to confirm that being the issue, but I cannot seem to find them myself.

**Comment by NULLYUKI** [comment]
According to patch [230932](https://www.teamfortress.com/post.php?id=230932)
> Fixed an issue with Blazehattan contracts 
Fixed an issue with Outburst contracts 

Please retest this issue.

**Comment by KimmyTF2** [comment]
Blazehattan Contract now works and all its objectives too

https://github.com/user-attachments/assets/0aba3b20-9dc8-453c-ac9b-7fb34974647b

![blaze](https://github.com/user-attachments/assets/c911f7ab-d512-419f-a5c3-8247aa3da5a2)

Outburst Contract's bonus objective "Win a round as a Merc"  works correctly.
 "Deal 1000 damage as a Merc" objective is still broken. https://github.com/ValveSoftware/Source-1-Games/issues/6435#issuecomment-2424165474

https://github.com/user-attachments/assets/506d3b07-71c6-4149-a117-6eeb42e4e8b2

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
