### ISSUE TITLE
[Portal] test chamber 19 behind the scene crash

### ISSUE THREAD

**Issue by vulam49** [ValveSoftware/Source-1-Games#7530]
So i'm playing portal on window for a while now and after switching to linux a came across a problem. After in beating chamber 19 I found that in the behind the scene, I tried to pass though the sewer, but i  came a cross a crash, so i tried again, but no luck, so I noclip pass but still no luck. The video below will demonstrate what i mean.

https://drive.google.com/file/d/1q9gih70VTeXapLiTUDlPTW3pe8Igo2Qq/view?usp=sharing

**Comment by HeroponRikiBestest** [comment]
Occurs for me as well (also on linux). This seems to be the same issue people were experiencing on February 14th where loading the sewer area causes the game to crash.

![Image](https://github.com/user-attachments/assets/14f9751a-beff-4452-b9e8-d529de864b4d)

**Comment by HeroponRikiBestest** [comment]
Probably worth updating the title to something more descriptive, given the issue at hand is loading a specific area towards the end of chapter 19. I know the steam discussion for this bug claims it was fixed, but having played from a fresh install and a new game, it occurs for me here.
https://steamcommunity.com/app/400/discussions/0/565867561337489169

**Comment by vulam49** [comment]
So here's one thing. I downloaded portal from internet archive (I know it pirating but it was uploaded by valve). The build on the archive was 19017868, so i checked steamdb.info patch in portal, 19017868. So I just downloaded the latest build, and it not fixed

**Comment by kisak-valve** [comment]
Hello @vulam49, we can not support pirated software.

**Comment by vulam49** [comment]
Wait, hold up. How the hell did escape 00 - 02 work? and the wired thing is it only work whe i don't move my camera?

**Comment by vulam49** [comment]
ok nvm escape 00 crash at the start
escape 01 crash on load
and ONLY escape 02 work no crash

**Comment by Sarajevo1914** [comment]
Today 2026-01-13 Portal 1 on steam archlinux native or any proton version crash
I cannot play this game :c

**Comment by miblo69** [comment]
Can confirm I also have the same issue. Running on Ubuntu 25.10, Wayland. Steam and Portal are updated to the latest versions, as of today.  This used to work flawlessly for years  - but something has changed recently. I upgraded from Ubuntu 24.04 LTS to 25.10 about a month ago. The OS upgrade may be the cause, but I don't know how to confirm if that is the case. Running on a Lenovo laptop.

Edit: I solved the issue with adding "-vulkan" to the startup option: Properties, General, Launch Options. Add "-vulkan". And I could complete the sewer in Chamber 19.
